### ISSUE TITLE
"Remove ctrl+left click to right click" dosen't work . Please help

### ISSUE THREAD

**Issue by Tim-zyt** [pqrs-org/KE-complex_modifications#1015]
"Remove ctrl+left click to right click" dosen't work . Please help.
m1pro、macOs-Monterey 12.0.1

```
{
  "title": "Remove ctrl+left click to right click",
  "rules": [
    {
      "description": "ctrl+left click to left click",
      "manipulators": [
        {
          "type": "basic",
          "from": {
            "pointing_button": "button1",
            "modifiers": {
              "mandatory": ["control"]
            }
          },
          "to": [
            {
              "pointing_button": "button1"
            }
          ]
        }
      ]
    }
  ]
}
```

**Comment by Tim-zyt** [comment]
{
  "title": "Remove ctrl+left click to right click",
  "rules": [
    {
      "description": "ctrl+left click to left click",
      "manipulators": [
        {
          "type": "basic",
          "from": {
            "pointing_button": "button1",
            "modifiers": {
              "mandatory": ["control"]
            }
          },
          "to": [
            {
              "pointing_button": "button1"
            }
          ]
        }
      ]
    }
  ]
}

**Comment by Tim-zyt** [comment]
`{
  "title": "Remove ctrl+left click to right click",
  "rules": [
    {
      "description": "ctrl+left click to left click",
      "manipulators": [
        {
          "type": "basic",
          "from": {
            "pointing_button": "button1",
            "modifiers": {
              "mandatory": ["control"]
            }
          },
          "to": [
            {
              "pointing_button": "button1"
            }
          ]
        }
      ]
    }
  ]
}`

**Comment by MuhammedZakir** [comment]
Have you seen this -- https://github.com/pqrs-org/KE-complex_modifications/issues/615 ?
