### ISSUE TITLE
How to I map home/end/pageup/pagedown to combos?

### ISSUE THREAD

**Issue by philipt18** [pqrs-org/KE-complex_modifications#102]
I'd like to add the following maps to Karabiner Elements, but I'm not clear how to do it.

Home - Command-C
End - Command-V
PageUp - Command-Alt-Shift-V
PageDn - Command-Shift-V

The simple modifications only lets me add one key, and the complex modifications only lets me download existing rules. How Do I create those mappings? I see in the docs for Karabiner about private.xml, but that doesn't seem to be in Karabiner Elements. Thanks.

**Comment by smlewis** [comment]
Complex modifications builds itself from a JSON file, at (for example) /Users/smlewis/.config/karabiner/karabiner.json.  This is the spiritual replacement for the old XML.  If you read through some of the sample JSON in this repo you will see how to build your own for the modifications you need.

**Comment by Profitsarts** [comment]
Hi!
I have the same issue but reading this I'm still not able to do it.
Can't add a double keystroke mapping / don't know hot to add a combo on the json file

Can anybody help me please?

Thanks

**Comment by yqrashawn** [comment]
@Profitsarts  Check out here 
https://github.com/pqrs-org/KE-complex_modifications/blob/master/docs/json/personal_yqrashawn.json#L401
Just add another key_code object in the array.

**Comment by tpj2018** [comment]
You can do this in Better Touch Tool. Karabiner & BTT are magic together.
