### ISSUE TITLE
Lock screen with f6

### ISSUE THREAD

**Issue by chlebta** [pqrs-org/KE-complex_modifications#1024]
I'm trying to remap the lock screen shortcut `command+control+q` to `f6` but it's not working.
`
{
  "title": "Lock Screen",
  "rules": [
    {
      "description": "f6 to Lock Screen",
      "manipulators": [
        {
          "type": "basic",
          "from": {
            "key_code": "f6"
          },
          "to": [
            {
              "key_code": "q",
              "modifiers": [
                "control",
                "command"
              ]
            }
          ]
        }
      ]
    }
  ]
}
`

What did I missed because it's not working.

**Comment by MuhammedZakir** [comment]
Any errors in Log tab in KE preferences? What is the output of Karabiner-EventViewer when pressing `f6` after applying the rule?

**Comment by chlebta** [comment]
Here's what I got : 
```
type:down            HID usage: 7,224     name:{"key_code":"left_control"}                             misc:flags left_control
type:down            HID usage: 7,227     name:{"key_code":"left_command"}                             misc:flags left_command,left_control
type:down            HID usage: 7,20      name:{"key_code":"q"}                                        misc:flags left_command,left_control
type:up              HID usage: 7,20      name:{"key_code":"q"}                                        misc:flags left_command,left_control
type:up              HID usage: 7,224     name:{"key_code":"left_control"}                             misc:flags left_command
type:up              HID usage: 7,227     name:{"key_code":"left_command"}                             misc:
```

**Comment by MuhammedZakir** [comment]
The rule is applied correctly. I don't why it is still not working.

Is there no option to set `f6` as lock screen shortuct in System Preferences?

**Comment by chlebta** [comment]
Nope nothing is system pref

**Comment by lihail-melio** [comment]
I'm not sure why you need `title` and `rules`, I removed them and it works:
``` json
{
    "description": "f6 to Lock Screen",
    "manipulators": [
        {
            "type": "basic",
            "from": {
                "key_code": "f6"
            },
            "to": [
                {
                    "key_code": "q",
                    "modifiers": [
                        "control", "command"
                    ]
                }
            ]
        }
    ]
}
```

**Comment by MuhammedZakir** [comment]
> I'm not sure why you need `title` and `rules`, I removed them and it works:

It is needed if you want to create complex modifications in `~/.config/karabiner/complex_modifications/<name>.json`.

https://karabiner-elements.pqrs.org/docs/json/root-data-structure/#custom-json-file-in-configkarabinerassetscomplex_modifications

> ```json
>  --snip--
> ```

So the shortuct for locking screen is `command+q` and not `control+command+q`?
