### ISSUE TITLE
Per window keyboard layout with karabiner

### ISSUE THREAD

**Issue by EvgeniiFrolov** [pqrs-org/KE-complex_modifications#1025]
Dear Karabiner,

First of all thanks for such a powerful app!
That’s great!

I’ve just switched to Monterey and being non-English speaker struggle with switching layouts between native one and English one.

I’ve been recommended to look at Karabiner-Elements to solve my issue. But having studied the project docs and having inspected complex rules web page I still can’t find a solution!

**Scenario:**
I use **two keyboard layouts**: English and non-English.
I often open **terminal**, where I use **English** layout.
And I often chat in **messaging** app using my **native** language.
I am tired of switching global keyboard **layout back and forth**.
I would like MacOS to remember, which layout was last-used in each window.

Is there a way to set up keyboard layouts preferences to have a separate layout for each window using karabiner?

My issue reports:
https://discussions.apple.com/thread/253361701
https://apple.stackexchange.com/questions/430801/separate-keyboard-layout-for-each-window-in-macos-monterey

**Comment by MuhammedZakir** [comment]
> I would like MacOS to remember, which layout was last-used in each window.
> 
> Is there a way to set up keyboard layouts preferences to have a separate layout for each window using karabiner?

Karabiner-Elements is not meant for this. Use Hammerspoon instead. It is the perfect tool for your use case.
