### ISSUE TITLE
Realforce Topre 23U Numpad not working on Mac 

### ISSUE THREAD

**Issue by Troif** [pqrs-org/KE-complex_modifications#1043]
Topre Realforce 23U numpad not working in Mac, only in Windows.

It appears that time ago a user in reddit solved it (@jm4ckie) and he introduced this code in the private.xml of the prior Karabiner version:

`<?xml version="1.0"?>
<root>
<item>
    <name>Realforce 23ub numlock force on</name>
    <identifier>private.realforce_force_numlock_on</identifier>
    <autogen>
        __ForceNumLockOn__
	DeviceVendor::RawValue::0x0853,
	DeviceProduct::RawValue::0x0117,
    </autogen>
</item>
<item>
    <name>Realforce 23ub Numlock fix</name>
    <identifier>private.pc_numlock_to_mac_numlock</identifier>
    <autogen>__KeyToKey__ KeyCode::KEYPAD_CLEAR,     KeyCode::VK_IOHIKEYBOARD_TOGGLE_NUMLOCK</autogen>
</item>
<item>
    <name>Realforce 23ub equal key fix</name>
    <identifier>private.realforce_eq_to_mac_eq</identifier>
    <autogen>
        __SimultaneousKeyPresses__
        KeyCode::KEYPAD_1, KeyCode::KEYPAD_6,     ModifierFlag::OPTION_L,
    KeyCode::KEYPAD_EQUAL,
</autogen>
</item>
</root>`

and there is no way to using it on new Karabiner version. 

I have a Realforce numpad and I'd like to use it. Could you help me out?

**Comment by MuhammedZakir** [comment]
This is not the place to ask. Please move this to Karabiner-Elements' repo. This is for complex modifications only.

---

First of all, I am not familiar with old Karabiner, so I may not be able to help you on this. Does EventViewer detects your numpad keypresses?
