### ISSUE TITLE
Mod request: App specific: Switch Cmd and Ctrl in VMWare/VirtualBox.

### ISSUE THREAD

**Issue by singalen** [pqrs-org/KE-complex_modifications#105]
I believe the title covers it.

**Comment by chocosando** [comment]
I agree. Is there any solution for swap (Cmd-Ctl) in Virtualbox ? 
Thank you,

**Comment by apm1467** [comment]
It has now been added under "Application Specific" section. Please let me know if it doesn't work right.

**Comment by singalen** [comment]
Thanks a lot!
Doesn't work in VirtualBox with guest Windows 7 32bit though: Ctrl is still Ctrl.

In my rules, I have Cmd and Opt swapped on both and right side.
