### ISSUE TITLE
Request: PC Style Shift-Home/End Selection Behavior

### ISSUE THREAD

**Issue by Mochnant** [pqrs-org/KE-complex_modifications#106]
Would it be possible to get an entry added for these:

- Shift-Home => Shift-Command-Left Arrow
- Shift-End => Shift-Command-Right Arrow

Thank you!

**Comment by TcT2k** [comment]
See #104 with the PC-Style Home/End that should work

**Comment by Mochnant** [comment]
Thank you, I did not think to check the PRs.  Much appreciated!
