### ISSUE TITLE
Issue with complex modification for left shift + right shift = caps_lock

### ISSUE THREAD

**Issue by perfectayush** [pqrs-org/KE-complex_modifications#107]
On OS X El Capitan with karabiner-elements version 0.91.13, when I use the rule for KE-complex_modifications/src/json/shift_lr_to_caps.json.erb, pressing both shift keys turns on the caps_lock as expected. But pressing both keys again, doesn't turn off caps lock. I am not sure if its a bug or the expected behaviour, or just an issue with El Capitan. 

I have been using karabiner for around 2 years. Not upgrading OS due to missing features in karabiner elements. I have been following the progress of karabiner elements, however. Thanks for everyone's effort. I might upgrade OS, once it has the features I require.

**Comment by apm1467** [comment]
Thanks for the bug report!

This issue has been fixed in #108 now. The new version of this rule has been moved into "Change shift key".
