### ISSUE TITLE
British Windows keys on mac

### ISSUE THREAD

**Issue by jamesgeddes** [pqrs-org/KE-complex_modifications#1109]
is there a way to easily translate *everything* on a windows keyboard to mac keys? I have an ergonomic windows keyboard and want to use it on my mac.

Incorrect keys include but are not limited to,

| character printed on keyboard | key combination according to keyboard | mac output |
| --- | -- | -- |
| " | shift + 2 | @ |
| ~ | shift + # | [bar](https://en.wikipedia.org/wiki/Vertical_bar) |
| [bar](https://en.wikipedia.org/wiki/Vertical_bar) | shift + \ | ± |
| print screen | PrtScn | _none_ |

**Comment by MuhammedZakir** [comment]
You will have to use complex modifications for that. You can use a gui or goku to make things easier. See the doc for links.
