### ISSUE TITLE
How can I map Key+Click combos?

### ISSUE THREAD

**Issue by SolusCado** [pqrs-org/KE-complex_modifications#111]
I'm trying to created a complex modification for Safari that remaps a Ctrl-Click to a Command-Click. I can create a modification that simply remaps left-control to left-command, and that works - but then of course it interferes with other shortcuts, like Ctrl-W, Ctrl-Tab, etc. I CAN create additional modifications for each of those shortcuts, but that's a bit of a pain. I've tried utilizing the "to_if_alone" mapping option, but it appears to do nothing (I'm guessing because the Ctrl-CLICK is recognized as "not alone"). Is there another option I can use to only map keys when used in conjunction with a mouse click?

**Comment by apm1467** [comment]
Currently, mouse click is not available in Karabiner-Elements. 

I think you've already listed all the options, and currently there's no other way to achieve your goal.

**Comment by kzsh** [comment]
@SolusCado You may be able to build the mapping you want with Karabiner-Elements 11.2.0 (currently beta).  See: https://github.com/tekezo/Karabiner-Elements/blob/4b386c4bfbd932573d09be3e6cf4c17de1bb5d95/src/apps/PreferencesWindow/PreferencesWindow/Resources/simple_modifications.json#L643
