### ISSUE TITLE
How to switch @ and " keys around on macOS

### ISSUE THREAD

**Issue by PlumpoChicken56** [pqrs-org/KE-complex_modifications#1116]
Hi,
I was trying to find a way to change the @ and " keys around on macOS (As i am using a windows keyboard with the key switched around. The " key would be activated when shift + 2 is pressed and the @ key would be actived when shift + ' is pressed.

Is there any preexisting .json files I could edit?

Thanks,
PlumpoChicken56

**Comment by MuhammedZakir** [comment]
https://github.com/pqrs-org/Karabiner-Elements/issues/3084
