### ISSUE TITLE
Keycodes ignored on Cherry KC 6000 Keyboard

### ISSUE THREAD

**Issue by fortysix2ahead** [pqrs-org/KE-complex_modifications#1168]
I am struggling to get a Cherry KC 6000 Slim to work with Karabiner. I would like to use the function keys as regular keys, not for media/volume control. Pretty straight-forward. But maybe some people here have an idea ...

First, the OS-setting "use Fn keys as function keys" seems to be ignored by the keyboard. Neither setting this option in the Mac Preferences (I am on Monterey) nor in Karabiner shows any effect. It works for the built-in keyboard of the Macbook, but not for the Cherry.

So I tried my luck with Karabiner's complex modifications. I was able to remap i.e. f5 to fn-f5. This works fine. I checked the Karabiner event viewer and all seems ok. However, it does not work with i.e f12. The event viewer simply does not show any activity, so I cannot see which keycode is sent. I tried to use a modification for f12 similar to the f5 one, but no luck. It seems that the keyboard sends something that causes "volume increase", but this is not detected by Karabiner. I guess this is also the reason why all the sets of modifications for fn-keys that can be downloaded do not work for this specific keyboard.

Any idea?

**Comment by fortysix2ahead** [comment]
This issue #985 seems to be related, however it's not a solution.

**Comment by MuhammedZakir** [comment]
Quit Karabiner-Elements (not just closing the window), open on-screen keyboard, and press `F12` on your keyboard. If the on-screen keyboard shows that keypress, it *maybe* possible to remap that key.2. 

EventViewer has "unknown events" (name maybe a little different), it will show key events not recognized by Karabiner. Check it to see whether it shows anything for `F12`.

P.S. you should report this in Karabiner-Elements' repo, not here.

**Comment by fortysix2ahead** [comment]
Sorry for reporting here, I'll close the issue and report it in the Karabiner repo. However, tried both suggestions without result. The on-screen keyboard displays normal key presses, but not F8 to F12. Same holds true for the unknown events: nothing to be seen in there.
