### ISSUE TITLE
need to publish to pqrs site

### ISSUE THREAD

**Issue by tyeraymond-design** [pqrs-org/KE-complex_modifications#1181]
need "  src/json/Tye Tartarus v2  " to be on the site for download to karabiner elements. How do I do this?

**Comment by tekezo** [comment]
Move it to `public/json/Tye-Tartarus-v2.json`.

**Comment by tyeraymond-design** [comment]
I attempted to do so, but it won't pass the checks for some reason. What is a way to verify this issue?

**Comment by tekezo** [comment]
The caused is invalid key_name in your json.

The `key_code: "+"`, `"["`, "space" are invalid key names.
https://github.com/pqrs-org/KE-complex_modifications/runs/7736780177?check_suite_focus=true

You can confirm the correct key name by EventVewer.
https://karabiner-elements.pqrs.org/docs/manual/operation/eventviewer/

**Comment by tyeraymond-design** [comment]
thank you!
