### ISSUE TITLE
new complex modification proposal

### ISSUE THREAD

**Issue by matijasss** [pqrs-org/KE-complex_modifications#12]
Could you please add this complex modification rule: https://www.marenauta.com/command_arrows_to_option_arrows.json to the page https://pqrs.org/osx/karabiner/complex_modifications/

**Comment by apm1467** [comment]
You can just do it yourself. 

Fork this project, clone the project files to your own computer, make the changes, and then open a pull request from your forked project to this original project. Just like what other people have done [here](https://github.com/pqrs-org/KE-complex_modifications/pulls?q=is%3Apr+is%3Aclosed).

This is how open source projects work. Give it a try. It's not hard.

**Comment by matijasss** [comment]
Done thanks!

Cheers

Mat


Il 08/07/17 05:27, Yi Ge ha scritto:
