### ISSUE TITLE
How can I add a new complex modification? 

### ISSUE THREAD

**Issue by mgiu96411** [pqrs-org/KE-complex_modifications#1229]
I'm trying to make a modification to turn F16 into a Macro to "Paste Values" in Excel. (I have no previous experience with .json and barely any with coding, so I'm not sure that it works)
From: F16
To:
1) CMD+ALT+V
2) V
3) Enter

But I can't add it to the repository because I need push access.

Here is the code:

`{ "title": "F16 to Paste Values (for Excel)",
  "rules": 
  [
    {
	    "description": "F16 to Paste Values (for Excel)",
        "type": "basic",
        "from": {
            "key_code": "f16"
        },
        "to": [
            {
                "key_code": "v",
                "modifiers": ["command", "option"]
            },
            {
                "key_code": "v"
            },
            {
                "key_code": "enter"
            }
        ]
    }
  ]
}
`
[F16_to_Paste_Values.txt](https://github.com/pqrs-org/KE-complex_modifications/files/9821173/F16_to_Paste_Values.txt)

**Comment by honsa** [comment]
Follow the docs, it is possible to make a pull request

https://karabiner-elements.pqrs.org/docs/manual/configuration/configure-complex-modifications/
