### ISSUE TITLE
Change Shift_Left + Shift_Right to Caps_Lock not turning off caps lock

### ISSUE THREAD

**Issue by paragbaxi** [pqrs-org/KE-complex_modifications#123]
Turns on caps lock. Doesn't turn off caps lock.

**Comment by paragbaxi** [comment]
https://github.com/pqrs-org/KE-complex_modifications/blob/master/docs/json/change_shift_l.json

**Comment by apm1467** [comment]
This issue was known and has already been fixed. 

Please import the newest version of the "Change shift key" rule from the official repository and see if it works for you.

**Comment by apm1467** [comment]
It turns out this file is an old version and hasn't been displayed on the index page. I've just removed it.

Thanks for pointing it out!
