### ISSUE TITLE
Single key to keystroke not releasing keystroke

### ISSUE THREAD

**Issue by wgj** [pqrs-org/KE-complex_modifications#124]
I'm trying to make a new complex modification for changing a single key (<kbd>insert</kbd>) into a keystroke (<kbd>option</kbd> + <kbd>esc</kbd>).  When I press <kbd>insert</kbd>, it's as if I never "let go" of <kbd>option</kbd>. See Event Viewer snippets below.

This really feels like I'm not writing the json correctly, as opposed to a bug. It's my first time writing a complex modification, so Occam's Razor suggests PEBKAC ;)

`personal_wgj.json.erb`
```
{
    "title": "Personal rules (@wgj)",
    "rules": [
        {
            "description": "Change insert to left_option+escape (VoiceOver)",
            "manipulators": [
                {
                    "type": "basic",
                    "from": <%= from("insert", [], ["any"]) %>,
                    "to": <%= to([["escape", ["left_option"]]]) %>
                }
            ]
        }
    ]
}
```

<kbd>left_option</kbd> + <kbd>esc</kbd>
```
eventType:FlagsChanged    code:0x3a       name:left_option     flags:Opt                                misc:
eventType:FlagsChanged    code:0x3a       name:left_option     flags:                                   misc:
```

<kbd>insert</kbd>
```
eventType:FlagsChanged    code:0x3a       name:left_option     flags:Opt                                misc:

```

**Comment by apm1467** [comment]
This actually looks right. You can append a `"vk_none"` after the keystroke to see what happens. It is a virtual key which terminates keystrokes and releases modifier flags.

```
{
    "title": "Personal rules (@wgj)",
    "rules": [
        {
            "description": "Change insert to left_option+escape (VoiceOver)",
            "manipulators": [
                {
                    "type": "basic",
                    "from": <%= from("insert", [], ["caps_lock"]) %>,
                    "to": <%= to([["escape", ["left_option"]], ["vk_none"]]) %>
                }
            ]
        }
    ]
}

**Comment by wgj** [comment]
Adding `"vk_none"` had desired behavior. Leaving it up to you to close as-is or investigate further. Thanks for your help!
