### ISSUE TITLE
F keys or touchbar does not work

### ISSUE THREAD

**Issue by pthieu** [pqrs-org/KE-complex_modifications#13]
I have this complex mapping:
```
{
      "description": "Change F6 to Left_command + L",
      "manipulators": [
        {
          "from": {
            "key_code": "f6",
            "modifiers": {
              "optional": [
                "any"
              ]
            }
          },
          "to": [
            {
              "key_code": "l",
              "modifiers": [
                "left_command"
              ]
            }
          ],
          "to_if_alone": [
            {
              "key_code": "l",
              "modifiers": [
                "left_command"
              ]
            }
          ],
          "type": "basic"
        }
      ]
    }
```

When pressing F6, it should trigger `cmd + L` (this is to select input bars like the url bar in chrome browser), but doesn't.

**Comment by kamykaze** [comment]
Where do you have this at? Make sure you have it under a "rules": [] section in either the karabiner.json file, or in a separate file under ~/.config/karabiner/assets/complex_modifications/

After adding that, check that you did not turn off the touchbar device under Preferences > Devices. The touchbar is treated as a separate keyboard and listed as "No product name (No Manufacturer name)"

I tried this myself and it worked without problems (well, sort of... I have some other mappings using BetterTouchTool that I had to turn off to avoid conflict)
