### ISSUE TITLE
complex mod: cmd+q twice to apply

### ISSUE THREAD

**Issue by paragbaxi** [pqrs-org/KE-complex_modifications#144]
I don't see any examples requiring a button to be hit twice. Any suggestions where I can start to learn how to code this?

**Comment by kzsh** [comment]
@paragbaxi, I believe you're right that it doesn't support mappings like that yet (see https://github.com/tekezo/Karabiner-Elements/issues/16).  This is a behavior that would have to be supported by https://github.com/tekezo/Karabiner-Elements itself.

**Comment by apm1467** [comment]
This rule has been added now.
