### ISSUE TITLE
Neo2 bindings only work for internal keyboard

### ISSUE THREAD

**Issue by SirVer** [pqrs-org/KE-complex_modifications#148]
I have an external keyboard attached to my mac (Matias Ergo Pro). I used to use https://github.com/jgosmann/Karabiner-Elements-Neo on 10.11 which worked perfectly. I had to update to 10.13 for unrelated reasons and found that the fork is no longer maintained.

Unfortunately, the new blessed way only works for my internal keyboard, but not for the externally attached one.

@jgosmann I see you just freshly created the Neo2 files in this repository - thanks for working on this! Can I provide any more information to debug the issue at hand?

**Comment by jgosmann** [comment]
I don't have an external keyboard handy to test this myself at the moment. Did you check the devices tab in Karabiner-Elements and verified that your external keyboard is selected there?

**Comment by SirVer** [comment]
@jgosmann Yes, it is enabled.

![image](https://user-images.githubusercontent.com/140115/31319831-2db6634a-ac6a-11e7-9212-43b9863fa202.png)

**Comment by jgosmann** [comment]
Can you let me know if jgosmann/KE-complex_modifications#1 helps?

**Comment by SirVer** [comment]
I will test this on the weekend and report back!

**Comment by jgosmann** [comment]
I added rules for Windows-style keyboards that should apply to most external keyboards and are based on the mappings listed in the issue I linked. Maybe that solves your problem?
