### ISSUE TITLE
Adding Local JSON File for Complex Rules

### ISSUE THREAD

**Issue by jeff-hykin** [pqrs-org/KE-complex_modifications#1492]
Hi! I'm a dev and would much rather edit a JSON file than click through a UI like https://genesy.github.io/karabiner-complex-rules-generator/

Is there some way to load a local JSON file as a complex rule? I've looked through the docs and the UI but can't seem to find a way.

**Comment by tekezo** [comment]
I think this feature has made things much easier.
https://twitter.com/tekezo/status/1700850618104222071

The implementation of a rich editor is not in plans at this time. It is too hard to implement.

**Comment by Nauxscript** [comment]
Maybe you could make a new rule by json and move it to the below path:
![image](https://github.com/pqrs-org/KE-complex_modifications/assets/13010589/60ad99d8-1f97-4f0e-8940-231c19a90fbd)

and then you can import that rule in app.

**Comment by jeff-hykin** [comment]
> The implementation of a rich editor is not in plans at this time. It is too hard to implement.

I totally understand, and if I wanted a rich editor I think the UI in that link is great. I'm looking for a plaintext solution.

> Maybe you could make a new rule by json and move it to the below path:

@Nauxscript 

Thanks! That's exactly what I was looking for. I want to sync settings between machines and edit the json directly. I haven't tested it yet, but I probably will later today. Hopefully it doesn't require setting up the development version of KE

**Comment by jeff-hykin** [comment]
Okay, I can confirm `~/.config/karabiner/assets/complex_modifications/` was exactly what I was looking for. It was also really helpful to have it for duplicating rules and making slight modifications to them.
