### ISSUE TITLE
Volume buttons to Opt Shift Volume (fine volume control)?

### ISSUE THREAD

**Issue by mrelwood** [pqrs-org/KE-complex_modifications#153]
I'm not able to make this work. I'm a noob, and there is no precise easy-to-follow guide on how to make my own complex modifications. So I probably did something wrong.

Goal is to have fine Volume controls without needing to press Option and Shift as well. I was surprised there isn't a ready model for this, as I've wanted this for years! Can it be done?

**Comment by bingocaller** [comment]
@mrelwood Try saving this as a JSON-file in your `~/.config/karabiner/assets/complex_modifications` folder:
```json
{
  "title": "Fine volume contol",
  "rules": [
    {
      "description": "Map volume controls to fine volume controls (Option + Shift + Volume)",
      "manipulators": [
        {
          "type": "basic",
          "from": {
            "key_code": "volume_decrement"
          },
          "to": [
            {
              "key_code": "volume_decrement",
              "modifiers": [
                "left_shift",
                "left_option"
              ]
            }
          ]
        },
        {
          "type": "basic",
          "from": {
            "key_code": "volume_increment"
          },
          "to": [
            {
              "key_code": "volume_increment",
              "modifiers": [
                "left_shift",
                "left_option"
              ]
            }
          ]
        },
        {
          "type": "basic",
          "from": {
            "key_code": "f11",
            "modifiers": {
              "mandatory": [
                "fn"
              ]
            }
          },
          "to": [
            {
              "key_code": "volume_decrement",
              "modifiers": [
                "left_shift",
                "left_option"
              ]
            }
          ]
        },
        {
          "type": "basic",
          "from": {
            "key_code": "f12",
            "modifiers": {
              "mandatory": [
                "fn"
              ]
            }
          },
          "to": [
            {
              "key_code": "volume_increment",
              "modifiers": [
                "left_shift",
                "left_option"
              ]
            }
          ]
        }
      ]
    }
  ]
}
```
You can do that by first copying the JSON from above, then running the following command in you terminal:
```bash
pbpaste > ~/.config/karabiner/assets/complex_modifications/fine_volume_control.json
```
It should then show up as an option in your Karabiner settings under Complex Modifications -> Add rule.
Hope it helps! 🙂

**Comment by mrelwood** [comment]
It didn't work directly, but I was able to slightly modify that to make it work! Finally! Thank you so much!!!

I removed the "fn" parameters from the mandatory modifiers for keys F11 and F12. It seems the reference to "volume_decrement" is what doesn't work as expected, but the keys must be addressed as "f11" and "f12".

But now it works! This is so cool!!! Thank you!

**Comment by bingocaller** [comment]
So what you're saying is the `volume_decrement`/`volume_increment` listeners don't work at all? I guess I should remove those and then update the `f11`/`f12` listeners to optionally accept `fn` as a modifier! :)

**Comment by mrelwood** [comment]
Yes, that is how I understand. Without modifying the code the volume controls worked normally by themselves, but pressing fn at the same time they worked as fine volume controls.

**Comment by bingocaller** [comment]
Alright, here's my updated attempt!
```json
{
  "title": "Fine volume contol",
  "rules": [
    {
      "description": "Map volume controls to fine volume controls (Option + Shift + Volume)",
      "manipulators": [
        {
          "type": "basic",
          "from": {
            "key_code": "f11",
            "modifiers": {
              "optional": [
                "fn"
              ]
            }
          },
          "to": [
            {
              "key_code": "volume_decrement",
              "modifiers": [
                "left_shift",
                "left_option"
              ]
            }
          ]
        },
        {
          "type": "basic",
          "from": {
            "key_code": "f12",
            "modifiers": {
              "optional": [
                "fn"
              ]
            }
          },
          "to": [
            {
              "key_code": "volume_increment",
              "modifiers": [
                "left_shift",
                "left_option"
              ]
            }
          ]
        }
      ]
    }
  ]
}
```
I'm gonna update it over on my PR (#154) as well. Thanks for testing! 😁

**Comment by mrelwood** [comment]
Yes, that works! And I can still access regular volume controls by pressing Cmd at the same time.

**Comment by bingocaller** [comment]
Cool, that's good.  
I just realised those rules will override F11/F12 _no matter what_, which is a problem, since you won't be able to access them as regular function keys via `fn` anymore. I've already split the rules into fn/non-fn rules, but I'll need to add a tweak to the non-fn rules in order to maintain function keys via `fn`.

**Comment by bingocaller** [comment]
I updated the PR. You should probably pull the new JSON from over there, or see if/when it gets merged! 🙂

**Comment by apm1467** [comment]
It has been merged into the official repository now.
