### ISSUE TITLE
How do I set tab navigation in apps from CMD-J/K to just J/K or just Q/W?

### ISSUE THREAD

**Issue by amarendra** [pqrs-org/KE-complex_modifications#157]
I am using https://pqrs.org/osx/karabiner/complex_modifications/#personal_settings (by @apm1467).

I wanted to map Vi like navigation w/o any modifier key - preferably just Q and W or any two adjacent keys. Can it be done? If so, how should I go about it?

**Comment by yqrashawn** [comment]
I think you may not want to map Q and W without modifier key to swtich tab. Cause when use are in text box (google search bar/ renaming filename in finder) Q and W will won't insert q or w charater.

If you use Command+q Command+w for tab navigation, you won't be able to use the build in function (quit application and close window) of macos.

And to answer your question, you can checkout these two patches below.

[0001-On-master-use-w-q-without-modifer-to-switch-tabs.patch](https://gist.github.com/yqrashawn/19bae668e565aebae52f7310a94d6dff#file-0001-on-master-use-w-q-without-modifer-to-switch-tabs-patch)
[0001-On-master-command-w-q-to-control-control-shift-tab.patch](https://gist.github.com/yqrashawn/20c0762ef5d3ec891a27e6b22e171e3d#file-0001-on-master-command-w-q-to-control-control-shift-tab-patch)

**Comment by amarendra** [comment]
I get you know. I coming from Vimium/Vimperator point of view. You are right. I should rather go for `CMD+<key>`

Yes, I would rather not use built in functions - closing tabs and quitting app. In fact for quitting app I am trying to set `CMD+ESC` and for closing the tab I am thinking of using `OPTION+x`

**Comment by yqrashawn** [comment]
So that's command+escape as command+q, option+x as command+w.
```json
{
  "description": "comand+escape -> command+q, opetion+x -> command+w",
  "manipulators": [
    {
      "from": {
        "key_code": "escape",
        "modifiers": {
          "mandatory": [
            "left_command"
          ]
        }
      },
      "to": [
        {
          "key_code": "q",
          "modifiers": [
            "command"
          ]
        }
      ],
      "type": "basic"
    },
    {
      "from": {
        "key_code": "x",
        "modifiers": {
          "mandatory": [
            "left_option"
          ]
        }
      },
      "to": [
        {
          "key_code": "w",
          "modifiers": [
              "command"
          ]
        }
      ],
      "type": "basic"
    }
  ]
}
```

**Comment by apm1467** [comment]
If you would like to emulate Vimium, what you maybe need is:

1. Press i to enter insert mode, so all the letters are just letters
2. Press esc to enter normal mode, so you can press letter keys to control apps, like j/k to change tab, t to create new tab, etc.

This is achievable in Karabiner-Elements.  Karabiner-Elements already supports mode variables. You can see and example usage in the [Vi Mode](https://github.com/pqrs-org/KE-complex_modifications/blob/master/src/json/vi_mode.json.erb) source file.

I might implement a Vimium emulator mode later when I have time. It looks interesting. You can also try to implement one yourselves. If you succeed, feel free to raise a pull request.

**Comment by apm1467** [comment]
I've add a new Vimium mode. You can try it. Maybe that's what you are looking for.
