### ISSUE TITLE
Layers similar to Pok3r's

### ISSUE THREAD

**Issue by jpablobr** [pqrs-org/KE-complex_modifications#168]
Is it possible or can someone point me in the right direction as to implementing something similar to a custom (without modifiers) layer?

I'd like to be able to implement something like a customisable caps-lock/layer/mode (e.g., when on, have arrow keys or "numpad" [or whatever] available without having to press a modifier).

**Comment by yqrashawn** [comment]
Do you mean this?  


Normal -> numpad 1 -> numpad 1    
After click caps_lock -> numpad 1 -> other key you want to bind
click caps_lock again -> back to normal mode

**Comment by jpablobr** [comment]
Sorry, I should've been more specific when I mentioned numpad or arrow-keys since some keyboards do have them (which I don't). What I meant was to be able to "lock" keys in a similar way as the [the Dimond Cursor complex modification](https://pqrs.org/osx/karabiner/complex_modifications/#diamond_cursor) but that instead of having to press, for example, fn+i for left-arrow-key I could just "lock" keys to that layer/mode and then be able to have "i" (without modifiers) be the left-arrow-key. 

I was thinking than maybe it could be possible via some key-combo that will load a complex-modification and then another one will set it back to the previous settings?

I basically want to be able to map my main alphanumeric keys to something else but only in that layer, and ideally be able to easily get in and out if ([un]lock it).

**Comment by yqrashawn** [comment]
You may want to check this.  

https://github.com/pqrs-org/KE-complex_modifications/blob/master/docs/json/personal_yqrashawn.json#L1478  

The slash mode map slash to `set_variable` `slash_mode` to 1 and map `tab` to comand+tab when `slash_mode`  variable is 1.    
In your case, you can use the `to_if_alone` to set some variable and map some keys to set it back in your new layer.

**Comment by yqrashawn** [comment]
Since it's pretty clear, I'll close the issue. Feel free to reopen it if you have other questions about this issue.
