### ISSUE TITLE
Add ghostty to rawBundleIdentifiers.terminal and friends

### ISSUE THREAD

**Issue by BlueSpaceCanary** [pqrs-org/KE-complex_modifications#1763]
Would be nice to have `com.mitchellh.ghostty` in the terminal identifiers so Ghostty gets excluded from e.g. emacs bindings without going in and editing rules' jsons locally 🙂 it looks like there's also a bunch of manual lists of terminal identifiers in various places so those too I guess?

Just filing an issue rather than sending a PR because I can't log into GitHub on my work computer (I'm writing on my phone), but I'm happy to write a PR myself later if that's preferred!

**Comment by tekezo** [comment]
Done https://github.com/pqrs-org/KE-complex_modifications/pull/1765
