### ISSUE TITLE
Noob question: How do I make custom rules show up in Karabiner?

### ISSUE THREAD

**Issue by dorian-grey** [pqrs-org/KE-complex_modifications#185]
I put my modified .json file in the local assets/complex_modifications folder. Now how do I get my rules to show up? The Github page says something about updating within KE's preferences, but I don't find any update button for rules (I remember that feature in Karabiner). Am I blind or have I fundamentally misunderstood something? Feeling pretty dumb right now ...

**Comment by casos92** [comment]
Mine were not showing up initially either, and I think it had something to do with the name I gave it.  My json file was "ControlToCommandUnlessVirtualMachine.json" and it wouldn't show up.  I renamed it to "1510089076.json" and it showed up.  So just try naming it similarly to something that exists in the complex_modifications folder.

**Comment by yqrashawn** [comment]
@dorian-grey @casos92 The complex_modifications folder is for imported (downloaded) complex_modification. If you want to put your complex modification in that folder, better use this repo to generate the html index of your complex modifications and import into KE.

You can also put your complex modifications in `~/.config/karabiner/karabiner.json` `["profiles"][<profile index>]["complex_modifications"]["rules"]`

**Comment by dorian-grey** [comment]
@yqrashawn Thank you very much, that worked. I had problems with indentation when I tried to create a new rule (no idea where I put a { instead of a [ ), so I just added it to an existing rule and it now works.

**Comment by yqrashawn** [comment]
I'll close this issue, feel free to reopen it if you still have problems.
