### ISSUE TITLE
What is key name definition for `§, ±` key?

### ISSUE THREAD

**Issue by nawa** [pqrs-org/KE-complex_modifications#194]
On British English keyboard I have key `§, ±` in place of ` key of US English 
What is name definition of this key?

**Comment by yqrashawn** [comment]
You can use `Karabiner-EventViewer.app` to find out names of keys on your keyboard.

To find other names, check [here](https://github.com/tekezo/Karabiner-Elements/blob/master/src/apps/PreferencesWindow/PreferencesWindow/Resources/simple_modifications.json).

**Comment by nawa** [comment]
Thanks, this helped. The name is `non_us_backslas`
