### ISSUE TITLE
Overrides for more of the macOS emac-like keys?

### ISSUE THREAD

**Issue by nathanlanza** [pqrs-org/KE-complex_modifications#197]
I.E. ctrl-e/ctrl-a/ctrl-k being overridden system wide to always force move-to-end/move-to-start/delete-to-end? I hate how some applications (anything Microsoft/Anki/many webpages) override these I'm trying to figure out a way to overrule them.

**Comment by apm1467** [comment]
[This](https://support.apple.com/en-us/HT201236) is the table of all macOS system wide shortcuts.

There is sadly no guarantee that a shortcut will always forced move-to-end/move-to-start/delete-to-end. 

If `ctrl + a/e` does not move to start/end, you can try to map it to `command + left_arrow/right_arrow`; and if `ctrl + k` does not delete to end, try map it to `shift + command + right_arrow` and then `delete`. But there's always a chance that this does not work either.

**Comment by nathanlanza** [comment]
Hmmm. Do you know how Cocoa handles application specific shortcuts? I figure I could do something hacky like attach lldb and manually override some of the menu item shortcuts, but I'm sure there's a simpler way. 

Or even, is there a symbol I can break on in lldb to examine the stack as a keyboard interrupt signal is sent up through the OS and to the application? 

Any ideas?
