### ISSUE TITLE
Dvorak (or bépo) keyboards

### ISSUE THREAD

**Issue by wysow** [pqrs-org/KE-complex_modifications#20]
Hello,

First thanks a lot for all your work on Karabiner!

I'm wondering if dvorak (or bépo) layouts will be included in Karabiner Elements has they were in previous versions of Karabiner?

**Comment by kamykaze** [comment]
this doesn't sound too hard. Probably a bit time consuming to write out each mapping, but should be no problem.

I'll try to work on this this week. One thing I'll probably try to do is find a way to easily map a set of keys to another, instead of having to write each rule individually.

**Comment by wysow** [comment]
Thanks a lot @kamykaze, if you need beta-tester I'm in! ;) Also I'm using a TypeMatrix keyboard with some special keys (copy-paste, ...) which where handled in previous versions of Karabiner, the problem is that I do not really see how to do this mapping in Karabiner Elements....

**Comment by kamykaze** [comment]
@wysow I've created a recipe for this in pull request #63 . I'll merge that after @tekezo has a chance to look at the changes.

If you'd like to try it out before it's merged, you can save a copy of this dvorak_layout.json to your ~/.config/karabiner/assets/complex_modifications/ folder

https://raw.githubusercontent.com/kamykaze/KE-complex_modifications/feature-dvorak/docs/json/dvorak_layout.json

**Comment by wysow** [comment]
@kamykaze Thanks a lot, you rocks!

**Comment by kamykaze** [comment]
Dvorak mode has been merged into master. I'm closing this.

Please create another issue for bépo if it's still desired. It is not as straightforward (due to different accent letters). I may take a look at that as well, but can't promise.
