### ISSUE TITLE
How to use the setting "lazy: true" ?

### ISSUE THREAD

**Issue by s-show** [pqrs-org/KE-complex_modifications#208]
There is a setting `"lazy": true` on line 264 of 'https://github.com/pqrs-org/KE-complex_modifications/blob/master/src/json/personal_tekezo.json.erb'. In what case should this `"lazy": true` setting be used?
I tried and tried to find out how to use the setting `"lazy": true`, but I could not grasp the details.
Does anyone know how to use the setting `"lazy": true` ?

**Comment by yqrashawn** [comment]
https://github.com/tekezo/Karabiner-Elements/issues/824#issuecomment-318810084
Maybe this is the explanation. I'm not sure. I'll try later.

**Comment by tekezo** [comment]
The modifier key will acts as lazy modifier with the `lazy` flag.
The lazy modifier does not send events until another key is pressed.

For example, if we use `lazy` flag with the following manipulator,
left_command event will not be sent if we press only left_command key.

```
- from: left_command
- to: left_command
- to_if_alone: escape
```

It's useful for apps which are recognize modifier key tapping to special purpose.
(e.g., Alfred which observes control key tapping.)

**Comment by s-show** [comment]
Thank you @tekezo . I understood how to use "lazy:".
