### ISSUE TITLE
How to map secondary button options to any symbol

### ISSUE THREAD

**Issue by SlieT** [pqrs-org/KE-complex_modifications#213]
Dear reader,

im trying to map option+o to ö instead of ø since im using an english keyboard on my mac but also need to write emails and stuff in german. 

how do i remap 
option+o => ö 
option+a => ä 
option+u => ü 
eg.
shift+option+o => Ö
shift+option+a => Ä
shift+option+u => Ü

Much thanks in advance .*

**Comment by apm1467** [comment]
Thank you for the idea. You can now import this "German Umlaut" rule from the index page.
