### ISSUE TITLE
Karabiner 11.3.10 vim mode

### ISSUE THREAD

**Issue by diegodesouza** [pqrs-org/KE-complex_modifications#241]
I've imported `Vi Style Arrows` to my `Complex Modifications` for a vim mode `Change Fn + h/j/k/l to Arrows` but it doesn't work. Does anyone know what extra steps I need to take in order to get it to work?

**Comment by apm1467** [comment]
Are you using Fn key on an Apple keyboard (like the build in one on a MacBook), or Fn key on an external keyboard from other brands? The latter will not work.

**Comment by diegodesouza** [comment]
I am using the `Fn` key on my MacBook @apm1467

**Comment by apm1467** [comment]
Have you enabled it after import?

![import](https://user-images.githubusercontent.com/10210967/33615998-de49cfdc-d9db-11e7-92ec-bb4cffa91377.png)

**Comment by diegodesouza** [comment]
Sorry it's taking me a long time to respond this. Yes i have enabled it there. I have also tried other settings to make sure it wasn't my `fn` key didn't work either.

**Comment by diegodesouza** [comment]
I can now verify that it works on my work laptop running macOS Sierra Version 10.12.6. I will double check my personal laptop version to compare (which is where doesn't work). What other info would be relevant for you? @apm1467

**Comment by diegodesouza** [comment]
My personal laptop is running off `10.13.1` so it should still work. I'm going to uninstall it and install it again, maybe that will do it.

**Comment by diegodesouza** [comment]
Closing. Ended up doing a complete reinstall and it's working now.
