### ISSUE TITLE
Is there a feature like '__SimultaneousKeyPresses__' in old version?

### ISSUE THREAD

**Issue by wxiaoguang** [pqrs-org/KE-complex_modifications#260]
The SimultaneousKeyPresses is very handy.

**Comment by toblich** [comment]
I haven't used the old version much to say if this is exactly the same or not, but I guess the new `"simultaneous"` feature covers what you were asking for. Check out [this usage example in the official docs](https://pqrs.org/osx/karabiner/json.html#typical-complex_modifications-examples-simultaneous-equal-delete-to-forward-delete).
