### ISSUE TITLE
macbook keyboard iSO switched with ANSI

### ISSUE THREAD

**Issue by PeterWagemans** [pqrs-org/KE-complex_modifications#272]
Hi,
Long time user of your excellent utility.

On the MacBook Pro 15"with touch bar and an ISO keyboard, the key mapping is changed to the mapping of an ANSI keyboard as soon as Karabiner starts up. So a `becomes a § and a § becomes a `.
This behaviour is on the INTERNAL keyboard.
If the virtual keyboard in Karabiner is set to the ANSI one, the INTERNAL keyboard behaves like an ISO keyboard, they EXTERNAL keyboard switches to ANSI.

SO, on the EXTERNAL Apple keyboard, the mapping is correct, the internal keyboard has its behaviour swtched.

The hardware on both keyboards is ISO US international QWERTY and the  keyboard control panel, tab "input sources" keyboard is set to the "U.S. International - PC" driver.

**Comment by PeterWagemans** [comment]
the backtick got lost in the editor, I see. The backtick key becomes the paragraph key and vice versa.

**Comment by PeterWagemans** [comment]
You are welcome Wall E, here's some activity so this bug report can be ignored for another 2 months.

**Comment by Birate** [comment]
Hey, I somehow had a similar problem between my MacBook Pro 13" and a Logitech Keyboard.
More users reports would be nice to identify the problem.
