### ISSUE TITLE
Does not enter `|` but instead `≤`

### ISSUE THREAD

**Issue by vonneudeck** [pqrs-org/KE-complex_modifications#285]
`Alt Gr + <`does not return a `|` but `≤` instead.
Weirdly enough if I enter `option + 7` without the rule enabled I do get a `|`.

https://github.com/pqrs-org/KE-complex_modifications/blob/41a9494d81ebd01198eae2d3cdb674d3d6d25d79/docs/json/german_pc_shortcuts.json#L110

**Comment by vonneudeck** [comment]
The issue is still there.
What would be the next step to debug this?

**Comment by PJWalker** [comment]
I don't have a german keyboard myself, but from setting things to german in software, it seems be working as intended here.

Can you open 'Karabiner-EventViewer', press your < key, and let me know what name it gives it?

**Comment by PJWalker** [comment]
This config is working as intended here.

It sounds like you're experiencing [Karabiner Elements  Issue #885](https://github.com/tekezo/Karabiner-Elements/issues/885). This seems to be a result of a conflict between Karabiner and the Keyboard Assistant, and a workaround is described on that page.

**Comment by vonneudeck** [comment]
I was indeed having the issue 885. The adverted workaround to not tell the macos-keyboard dialogue about the iso-ness of my keyboard helped. Thanks for telling me about it.
