### ISSUE TITLE
Press key once to do A, twice to do B

### ISSUE THREAD

**Issue by randke** [pqrs-org/KE-complex_modifications#290]
Not even sure how to name the title of this problem. Anyway, I have followed the examples out there to the best of my ability and still can’t figure out a proper solution. Basically, what I want to achieve is this:

If I press "t" once, then output "r". But if I press "t" twice (sort of like double clicking a mouse button) then output "y". So far that works. But the problem is that "r" also get output along with "y". How do I mute "r" from being output and only allow "y" to get through? Is this even possible?

**Comment by haakonstorm** [comment]
Hey, why was this closed? I'm having the same problem. Did you solve this somehow?
