### ISSUE TITLE
Colemak modification uses non-existant modifiers left_alt and right_alt

### ISSUE THREAD

**Issue by Grazfather** [pqrs-org/KE-complex_modifications#296]
See [here](https://github.com/pqrs-org/KE-complex_modifications/blob/master/src/json/colemak_layout.json.erb#L3)

Should probably be `left_option` and `right_option`.

**Comment by Grazfather** [comment]
This is still an issue.

**Comment by Grazfather** [comment]
@tekezo why would you ignore this PR?

**Comment by tekezo** [comment]
Could you make a PR?
