### ISSUE TITLE
Disable CMD + Tab

### ISSUE THREAD

**Issue by samlandfried** [pqrs-org/KE-complex_modifications#301]
I want to disable window switching via CMD + Tab. Modifying it to have no effect would be ideal, but remapping the combo to CMD + Q would work too (To punish user for trying to window switch).

**Comment by jimpsson** [comment]
I created a [gist](https://gist.github.com/jimpsson/c1256a6d42049d53d5d7390af2bc24bf) containing a set of two rules that solves what your trying to do. In short, I've created one rule that disables the application switcher, and another which disables command+q (no more accidental quits, hehe).

**Comment by Birate** [comment]
@jimpsson Feel free to had your modification to the repo, if it isn't already done 😄
