### ISSUE TITLE
Additional complex modifications

### ISSUE THREAD

**Issue by csexton** [pqrs-org/KE-complex_modifications#311]
I've made a number of complex modifications that are (slightly) different than most of the ones that are on the https://pqrs.org/osx/karabiner/complex_modifications page. 

I wrote up a blog post a while back about it, which can be seen [here](http://www.codeography.com/2017/07/16/the-next-era-of-remaping-caps-lock.html), and the rules can be imported from here: 

```
karabiner://karabiner/assets/complex_modifications/import?url=https%3A%2F%2Fraw.githubusercontent.com%2Fcsexton%2Fcsexton.github.com%2Fmaster%2Fkarabiner%2Frules.json
```

My question is, do you want me to submit a pull request with these modifications? I'd be happy to, but figured I should ask first 😄

**Comment by bingocaller** [comment]
Hi @csexton,

I checked out your blog post and your `Caps Lock` to `Ctrl`/`Escape` binding is already available as a part of the [Modern Space Cadet bindings](https://pqrs.org/osx/karabiner/complex_modifications/#space_cadet) (they can all be activated individually if you don't want the Hyper Key/Better Shifting stuff) and your `Ctrl`/`Command`+`hjkl`-bindings are already available as part of [Vi Style Arrows](https://pqrs.org/osx/karabiner/complex_modifications/#vi_style_arrows) so there's no real need to do a pull request for those.  
That being said, if you like having your particular bindings as part of a single set, someone else might like it too! You can always do the pull request and see if there's any interest! :)

BTW, I think you would like [Steve Losh's blog post](http://stevelosh.com/blog/2012/10/a-modern-space-cadet/) if you haven't already read it!

**Comment by csexton** [comment]
Thanks @bingocaller. I think I am a bit late to the game, many of those were not available back when I wrote the blog post. I should have sent a pull request then! I will look through and see if there is anything else that I use that might be missing and send a pull request. 

Thanks for the tip on Steve's blog post, I hadn't seen that. Weirdly relevant since I just spent the week building and programming a mechanical keyboard -- hell bent on making it support my Karabiner mappings directly.

❤️ for all the work on this project, it makes my interaction with my computer much happier.

**Comment by bingocaller** [comment]
You should definitely have submitted a pull request then! It's never a bad time to submit a pull request! 😁

Ooh, which keyboard did you build? I'm looking for a good, programmable board at the moment. 🙂

**Comment by csexton** [comment]
I built a GH60. I have some details for this build in [this repo](https://github.com/csexton/gh60-spaceman-spiff).

Definitely recommend the QMK firmware based boards :100:

**Comment by bingocaller** [comment]
I've seen a few GH60s around. They look very good. The prospect of all that soldering is a bit daunting, though. 😄
Do you know how it compares to a Pok3r or KBParadise V60 Type R?
