### ISSUE TITLE
How to disable Return key sending in iMessage and Facebook

### ISSUE THREAD

**Issue by stefic23** [pqrs-org/KE-complex_modifications#314]
I am very new to KE and cannot work out how to do this. I keep sending messages in imessage (also WhatsApp, and Facebook) by accidentally pressing the return key on my macbook, and the message either isn't finished, or isn't checked or edited. Can be very embarrassing.

Sorry if this question is in the wrong section or has been answered. I searched but couldn't find anything that might help.

I would rather the return key goes to the next line, and the Option+Return sends the message, rather than the other way around! Any help would be great.

**Comment by Birate** [comment]
The better way to achieve this behaviour, is to go for coding your own complexe mod.

1. Pull the repo somewhere
2. Create an `.erb` file with the modification you need. Exemple [here ](https://github.com/pqrs-org/KE-complex_modifications/blob/master/src/json/xcode.json.erb)
3. use the `make` command to generate a `.json` file; then put it under `$HOME/.config/karabiner/asset/complex_modification`
4. Test it
5. Repeat till done

Optional: Pull your config to this repo to share it
