### ISSUE TITLE
Is there any way to rotate screen?

### ISSUE THREAD

**Issue by vietvudanh** [pqrs-org/KE-complex_modifications#323]
I am using an external monitor with a monitor arm. Sometime I want vertical, for reading long codes and documents. Therefore I change between sometimes, might be 1-2 times a day. 

So it would be nice to be able to do that in key mapping instead of using system settings

Thanks!

**Comment by muyinliu** [comment]
Try [fb-rotate](https://github.com/CdLbB/fb-rotate).

**Comment by vietvudanh** [comment]
@muyinliu Thanks, that's a way but might be the best. I will try.
