### ISSUE TITLE
New rule request

### ISSUE THREAD

**Issue by djslacker** [pqrs-org/KE-complex_modifications#335]
Hello, I am new to this community and to coding so I figured this would be a faster solution.  I downloaded Karabiner and discovered that I would need to write code to implement a custom key-combo.  So, instead of trying to learn how to code just to do this, would someone mind creating a Karabiner rule that allows me to assign the key combo (Shift (either) + Option (either) + Space) to a single key?  I would really appreciate it.

**Comment by yqrashawn** [comment]
https://github.com/pqrs-org/KE-complex_modifications/blob/master/docs/json/nonbreaking_space.json#L23

this file, 
change line 23 to `a` then `left_option + space` is maped to `a`
change line 43 to `a` then `right_option + space` is maped to `a`
change line 13 to `left_shift` then `left_shift + space` is maped to `space`
change line 33 to `left_shift` then `left_shift + space` is maped to `space`

**Comment by djslacker** [comment]
Would you solution still mean that I need to hit A and Space to make the 3 key combo?

**Comment by djslacker** [comment]
It took me this long to find a decent .json editor and figure out how to test the file locally.  BTW, I'm on a Mac.  I'm not dumb, I just grew up with Windows so doing DOS level tasks on OSX is still slow for me.

**Comment by yqrashawn** [comment]
`left_option + space` is maped to `a`
 means press `left_option` down then `space` down will inert `a`

You can use the Karabiner-EventViewer.app to check if your mapping works.
