### ISSUE TITLE
[Request] switch to standard function keys in virtual env 

### ISSUE THREAD

**Issue by holymonson** [pqrs-org/KE-complex_modifications#376]
I want to standard function keys in virtual environment, i.e. use normal f1, f2 without fn. However, according to [Input event modification chaining], modification for function keys in `Complex Modifications` will be changed in `Function Keys Modifications` anyway.

    Karabiner-Elements treats input events by the following order:

        1. Catch events from hardware.
        2. Apply Simple Modifications.
        3. Apply Complex Modifications.
        4. Apply Function Keys Modifications (change f1...f12 keys to media controls).
        5. Post events to applications via a virtual keyboard.

So, is there a parameter in `complex_modifications` to skip stage `Function Keys Modifications`? Or how can we implement this request?

[Input event modification chaining]: https://pqrs.org/osx/karabiner/document.html#event-modification-chaining

**Comment by tekezo** [comment]
Change f1 key to fn+f1 in Complex Modifications.
