### ISSUE TITLE
Can I configure Capslock to cmd + alt + ctrl(hyper key)

### ISSUE THREAD

**Issue by cksachdev** [pqrs-org/KE-complex_modifications#383]
I am trying to configure Karabiner for hyper key and hyper+shift key. I have a version of Karabiner (Karabiner-Elements-0.90.68.dmg) which was custom with support for my needs. I have upgraded to macOS Mohave and the custom build doesn't seem to be working any more. I have downloaded latest version of Karabiner 12.1.0 and tried to customise a complex modification. https://pqrs.org/osx/karabiner/complex_modifications/#caps_lock
I have done following modification:
```
"rules": [
                    {
                        "manipulators": [
                            {
                                "description": "Change caps_lock to command+control+option+shift.",
                                "from": {
                                    "key_code": "caps_lock",
                                    "modifiers": {
                                        "optional": [
                                            "any"
                                        ]
                                    }
                                },
                                "to": [
                                    {
                                        "key_code": "",
                                        "modifiers": [
                                            "left_command",
                                            "left_option",
                                            "left_control"
                                        ]
                                    }
                                ],
                                "type": "basic"
                            }
                        ]
                    }
                ]
```

I can't find what value should go under "key_code". I have tried adding "modifiers" array in key_code property, but that doesn't seem to work and throws an error in logs. I have tried looking at other complex modifications json, but can't figure it out. Please help how I can achieve the desired settings.

**Comment by BlitZz96** [comment]
First off; What errors does this throw in the console?
You could also try to have `left_command` as `key_kode` and then add `left_option` & `left_control` as modifiers.
