### ISSUE TITLE
プルリクしたルールを取り込んでいただきありがとうございました！んがしかし…

### ISSUE THREAD

**Issue by tkatochin** [pqrs-org/KE-complex_modifications#386]
Webでも公開されたので、さっそくImportしたのですが、Karabiner-Elementsには以前のルールしか出てきません。
私の追記したルールは含まれないようです。WebからJSONを見る限りでは含まれているのですが…。
ブラウザのデバッガで見ると、karabiner://import... の通信ステートはキャンセルされた状態になってます。
あらかじめ、~/.config/karabiner/assets/complex_modifications は空にしてからKarabiner-Elementsを起動しています。
どこか別の場所にキャッシュされているのでしょうか？

**Comment by tekezo** [comment]
こちらの手元だとちゃんと新しいJSONが落ちてきていますが、今でも同じ症状が出ていますでしょうか？
明示的なキャッシュはしていませんが、間にプロキシが入っているか、Karabiner-Elements Preferencesを一度閉じるまでは古い内容が使われるということがあるかもしれません。
ブラウザ側では`karabiner://import...`はアプリの起動になるため、通信ステートがキャンセル扱いになるのは正しい挙動だと思います。

**Comment by tkatochin** [comment]
試してみたところ今回は正しく取れました。その時はKarabiner-Elementsを終わらせても再起動しても駄目だった記憶があるのですがなんでしょうかねー。プロキシも使っていません。
まずは解決したのでクローズします。今後またあった時はより詳細に情報を捉えたいと思います。
ありがとうございました。
