### ISSUE TITLE
Matias Ergo Pro: Change right Home/End keys to Right Option

### ISSUE THREAD

**Issue by wizonesolutions** [pqrs-org/KE-complex_modifications#39]
So the Matias Ergo Pro keyboard is missing a right option key. This bugs me because I often use the option key to type åøæ when typing Norwegian, as this saves me having to switch keyboard layouts. How would I go about setting up this mapping?

**Comment by smlewis** [comment]
If you mean "right Home OR right End to right Option" - you can set that up as two separate simple modifications, I think, in the simple modifications tab.

If you mean "right Home AND right End to right Option" - you'll need to edit your karabiner JSON that builds the complex modifications tab.  (/Users/yourname/.config/karabiner/karabiner.json).  Take a look at the modifications in the docs https://github.com/pqrs-org/KE-complex_modifications/tree/master/docs/json or https://github.com/tekezo/Karabiner-Elements/tree/master/examples - you'll see pretty quickly how to set up a JSON that does what you want.  https://github.com/pqrs-org/KE-complex_modifications/blob/master/docs/json/change_command_l.json is pretty close.

**Comment by wizonesolutions** [comment]
The EventViewer shows those home and end keys as sending the same code as Fn/left, Fn/right (which I had planned to use instead). Am I out of luck here?

**Comment by smlewis** [comment]
I don't know.  I think there is a separate tool in KE to let you remap what Fn + keys do - maybe you can get the latter to override the former?  If it's sending literally the same code then it sounds like it's keyboard firmware and you can't interact with it in this way.

**Comment by bingocaller** [comment]
@wizonesolutions I think you could use `to_if_alone` to great effect in your case.
Consider this rule:
```json
{
  "description": "Change right Home/End keys to Right Option.",
  "manipulators": [
    {
      "type": "basic",
      "from": {
        "key_code": "left_arrow",
        "modifiers": {
          "mandatory": [
            "fn"
          ]
        }
      },
      "to": [
        {
          "key_code": "right_option"
        }
      ],
      "to_if_alone": [
        {
          "key_code": "home"
        }
      ]
    },
    {
      "type": "basic",
      "from": {
        "key_code": "right_arrow",
        "modifiers": {
          "mandatory": [
            "fn"
          ]
        }
      },
      "to": [
        {
          "key_code": "right_option"
        }
      ],
      "to_if_alone": [
        {
          "key_code": "end"
        }
      ]
    }
  ]
}
```
If you add this to your `rules` in `~/.config/karabiner/karabiner.json` it will remap your Home/End keys to right Option when held down, while still working as Home/End on single press.
