### ISSUE TITLE
Help translating Karabiner rule (in XML) to Elements

### ISSUE THREAD

**Issue by nikitavoloboev** [pqrs-org/KE-complex_modifications#394]
I am trying to translate my configuration from old Karabiner to Karabiner Elements and I have one issue with how I can translate one rule from it to Elements.

[This code](https://github.com/nikitavoloboev/dotfiles/blob/master/karabiner/private.xml#L5073) in old Karabiner made `s` key a modifier key. Which means that I could press `s` key and hold it and then the next keys I press will be changed. 

This particular rule then defines keys and what actions they call when they will be pressed. For example [this block](https://github.com/nikitavoloboev/dotfiles/blob/master/karabiner/private.xml#L5130) will make it so that if I press and hold `s` key, then while holding s I press `g` key, then it will trigger `cmd + tab`.

I can't find a way how to define these kind of complete blocks in Karabiner Elements where I can tell Karabiner that this key is a new modifier key and then map actions underneath it like I could with old Karabiner. I've read through the entirety of JSON spec by @tekezo and it doesn't mention anywhere how one could do it.

Is this feature still not supported on Karabiner Elements?

**Comment by nikitavoloboev** [comment]
Hi @yqrashawn 

Does Elements support variables? I see in your config you call shell scripts inside the rules. I want to create variables for that and call them instead.

@tekezo Does Karabiner Elements support variables?

**Comment by nikitavoloboev** [comment]
Actually I realized Elements had this function:

```json
"set_variable":{
 "name":"alfred_searchio",
 shell_command":"osascript -e 'tell application \"Alfred 3\" to run trigger \"google\" in workflow \"net.deanishe.alfred-searchio.old\" with argument \"\"'"
}

But I can't figure out how I can define these before my rules definitions. I want to have something like `profiles:` block where I can define these in succession. Is it possible to do this?

**Comment by yqrashawn** [comment]
@nikitavoloboev it's different to old xml definition, you don't need to define variable before using them like `vkopenurldef`.
The `set_variable` is mainly using for archiving "layer" concept ([your sticky key](https://github.com/yqrashawn/yqdotfiles/blob/master/Library/Application%20Support/Karabiner/private.xml#L1901)).
Use `set_variable` to [define a variable](https://github.com/pqrs-org/KE-complex_modifications/blob/master/docs/json/personal_yqrashawn.json#L1121), and [use it as a condition](https://github.com/pqrs-org/KE-complex_modifications/blob/master/docs/json/personal_yqrashawn.json#L1159) in later rule.

**Comment by nikitavoloboev** [comment]
Thank you @yqrashawn
