### ISSUE TITLE
change fn+backquote to extended ascii char (lozenge)

### ISSUE THREAD

**Issue by jbshirk** [pqrs-org/KE-complex_modifications#397]
The Pollen language uses the lozenge extended acii char &#9674; as a function directive. Is there a way to assign a hardware key combination (I choose fn`) to type that character in a text editor?

**Comment by apm1467** [comment]
The key combination option + shift + V will output ◊.

**Comment by jbshirk** [comment]
̌ is what I'm getting.

**Comment by jbshirk** [comment]
I'm using ABC-Extended keyboard (Note: I have a MacBook Pro, so those keys to the right aren't there.)
![abc extended-opt-shift](https://user-images.githubusercontent.com/3949396/43484481-7761c024-94dc-11e8-9d80-a17162a92832.png)

**Comment by jbshirk** [comment]
I just tried with "ABC" (not extended) keyboard and that resolves the problem.
