### ISSUE TITLE
Why can't I pass modifiers in launcher mode ruby script

### ISSUE THREAD

**Issue by nikitavoloboev** [pqrs-org/KE-complex_modifications#399]
I have a script in ruby I modified from @tekezo. It works for nearly everything I need except for one method.

Here is the [method I use](https://github.com/nikitavoloboev/karabiner-generator/blob/master/karabiner-generate.rb#314). The issue is that when I then [call it](https://github.com/nikitavoloboev/karabiner-generator/blob/master/karabiner-generate.rb#L49).

It doesn't actually make Karabiner, when q key held down and then w key pressed trigger `cmd+shift+w`. You need to press it two times it seems to trigger.

Why is that?

**Comment by nikitavoloboev** [comment]
I managed to make the method work but it only works if I press and hold q key and then press the other key two times not one. 

Strangely, the [shell method](https://github.com/nikitavoloboev/karabiner-generator/blob/master/karabiner-generate.rb#L87) works as I want it to work. It triggers the action as it should. 

Thank you for any help.

**Comment by nikitavoloboev** [comment]
Also after I do press the other key two times, if the key my trigger key is still being held, then other activations will be activated on first try. 

I just don't get why I need to press the other key two times at first.

**Comment by apm1467** [comment]
Note you need braces in `to` definitions:

```
'to' => [
    Karabiner.set_variable(held_key, 1),
    { 
        'key_code' => key_code,
        'modifiers' => to_modifiers
    }
]
```

The Karabiner.set_variable() method adds braces for you, but you need to manually write braces if you are defining `key_code` and `modifiers` directly.
