### ISSUE TITLE
How to make a rule to insert multiple keycodes with unique modifiers?

### ISSUE THREAD

**Issue by nikitavoloboev** [pqrs-org/KE-complex_modifications#400]
In old Karabiner I could do this:

```xml
<autogen>
__KeyToKey__
KeyCode::B,
KeyCode::T, ModifierFlag::SHIFT_L,
KeyCode::O, ModifierFlag::SHIFT_L,
KeyCode::D, ModifierFlag::SHIFT_L,
KeyCode::O, ModifierFlag::SHIFT_L,
KeyCode::SEMICOLON, ModifierFlag::SHIFT_L,
KeyCode::SPACE,
</autogen>
```

Which made it so that if B key is pressed, `TODO: ` will be pasted.

I can't figure out how to do it in Karabiner Elements. Is it possible to do?

**Comment by yqrashawn** [comment]
Check out this. Just put multiple `key_code` into `to`.

https://github.com/pqrs-org/KE-complex_modifications/blob/master/docs/json/personal_yqrashawn.json#L1232
https://github.com/pqrs-org/KE-complex_modifications/blob/master/src/json/personal_yqrashawn.json.erb#L594
