### ISSUE TITLE
CAPS to_if_alone post ESC delay problem?

### ISSUE THREAD

**Issue by JesseLeite** [pqrs-org/KE-complex_modifications#405]
By default [this complex mod](https://github.com/pqrs-org/KE-complex_modifications/blob/a8caed14118beb82a0262e38ea5110cdcd7268ed/docs/json/vi_mode_with_caps_lock.json) lets me use `hjkl` as arrows when `CAPS` is held 👌   However, if `CAPS` is tapped alone, I want it to post `ESC`.  I've added `"to_if_alone": [{ "key_code": "escape" }]` to this section:

https://github.com/pqrs-org/KE-complex_modifications/blob/a8caed14118beb82a0262e38ea5110cdcd7268ed/docs/json/vi_mode_with_caps_lock.json#L78-L102

This does work, but there's a delay before `ESC` is posted.  Any idea why it's not as instant as pressing the actual `ESC` key?

**Comment by JesseLeite** [comment]
_Side note:_  In Windows I was able to create this [autohotkey]() script to do the same thing:

```
SetCapsLockState, AlwaysOff

CapsLock::
    KeyWait, CapsLock
    If (A_PriorKey="CapsLock")
        Send {Esc}
Return
#If, GetKeyState("CapsLock", "P") ;CapsLock modified hotkeys go below

h::Left
j::Down
k::Up
l::Right
```

Is it possible to script karabiner modifications?  While I appreciate the JSON approach, that is a very short code snippet that allows CAPS+hjkl, posts ESC when CAPS is pressed alone, and there's no perceivable delay when it posts ESC 👍

Scripting question aside, it'd be nice to know what's causing the delay with Karabiner in MacOS 🤔

**Comment by apm1467** [comment]
`to_if_alone` does have to wait. If it just sends esc as soon as you press the caps_lock key, you will always get esc + arrow keys (instead of only arrow keys) when you press caps_lock and H J K L keys together. 

The `to_if_alone` event will be triggered:
1.  after you press down and release the caps_lock key, or 
2. after you press down the caps_lock key for some time and do not press another key

You can change that time threshold in case 2 in Karabiner-Elements => Complex Modifications => Parameters => to_if_alone_timeout_milliseconds.

But `to_if_alone` will always have a delay. The whole point of `to_if_alone` is to wait and see if this key press is really "alone". If you want instant trigger without delay, you can just use `to`.

**Comment by JesseLeite** [comment]
Shoudn't have to wait on a millisecond timer though.  I wrote an Autohotkey script to do this in Windows.  It hooks onto both keydown and keyup events.  So if you tap CAPS, you get this in the event log:

- CAPS key down (pressed)
- CAPS key up (released)

First you listen on CAPS key up event, then you do a quick check on the previous event.  If the previous event was a CAPS key down event, then you know it was pressed alone (and not with any other key as a modifier).  Then you can process the to_if_alone directly without any sort of millisecond timeout.

Does that make sense?  Not sure why it requires a timeout.  Curious on your thoughts @apm1467 and @tekezo (I apologize for the ping, but curious on the design philosophy of the timeout here)?

**Comment by apm1467** [comment]
You are correct. Actually you just described the first case I described:

> 1. after you press down and release the caps_lock key

So if you press down and release the caps_lock key, esc should be sent immediately after you release.

(The second case was, if you press down and not release caps_lock, esc will still be sent if you hold down caps_lock for some milliseconds.)

I said "`to_if_alone` will always have a delay", what I meant was that "press down and release" is also a kind of delay. It is not the same as `to`, which will send esc immediately after you press down the key, and not wait for your release.

If you press down and release caps_lock, and there is still a delay between key releasing and esc firing, then there is a problem. Did you experience this?

**Comment by JesseLeite** [comment]
Gotcha, thanks for reply!

>If you press down and release caps_lock, and there is still a delay between key releasing and esc firing, then there is a problem. Did you experience this?

Yeah I'm thinking it's the perceived delay and/or processing time of it firing on keyup instead of the standard keydown.  If I hold down for a split second, it feels instantaneous when I release it 👍
