### ISSUE TITLE
Vim Mode 5.0 might be broken (4.3 works)

### ISSUE THREAD

**Issue by amirrajan** [pqrs-org/KE-complex_modifications#406]
Not sure if it's just my machine or if it's a global issue, but neither d or s as modifier seem to work in 5.0. I reverted back to 4.3 and my keys started working again:

OS: High Sierra
Karabiner Version: 12.1.4

**Comment by amirrajan** [comment]
Lemme see if I can dig in and get some more detailed repro steps (at least it works on someone else's machine 👍).

**Comment by apm1467** [comment]
If you never changed your `simultaneous_threshold_milliseconds` default setting, this is most likely the reason. Vi Mode rev 5 requires user to set this setting higher. Maybe I should state this more clearly in the description.

I personally set it to 170. A value between 150 and 500 should work fine.

PS. I enjoyed your game. Thank you for making it. It is a pleasure to know you also use Karabiner-Elements and Vi Mode.

**Comment by amirrajan** [comment]
>PS. I enjoyed your game.

😲 Such a small world. Dude I love vim mode. I get really angry on other machines when I cant press and hold "d" and do all the simple vim stuff. Email me (ar@amirrajan.net) and hook you up with download codes for all my other games (assuming you have an iOS device). I'll play around with the thresholds and get back to you as soon as I can verify what's going on.
