### ISSUE TITLE
Add an option to enable on startup

### ISSUE THREAD

**Issue by stanislasdrg** [pqrs-org/KE-complex_modifications#417]
Hello,
it would be great if the app could start at boot. Atm the easiest way is to leave the icon displayed, but it kind of clutters the top bar for anyone that already has Gdrive sync, Docker and default ones.

Thanks !

**Comment by bingocaller** [comment]
I think the app starts at boot per default? Do you also want to open the Karabiner-Elements preferences at boot or am I reading your question wrong?

**Comment by stanislasdrg** [comment]
Odd, sometimes it does not start by default. Some other times it work. Something might be wrong on my end. Closing for now.

**Comment by bingocaller** [comment]
Maybe also copy your configuration to the system default configuration? (Karabiner-Elements Preferences → Misc → System Default Configuration)
