### ISSUE TITLE
Help with generating JSON to scroll with launcher key

### ISSUE THREAD

**Issue by nikitavoloboev** [pqrs-org/KE-complex_modifications#421]
I am writing a [language to easily generate Karabiner configuration](https://github.com/nikitavoloboev/karabiner-generator). 

One thing I can't figure out how to do is scrolling. I have a [ruby method](https://github.com/nikitavoloboev/karabiner-generator/blob/master/karabiner.rb#L9) that creates a launcher key and assigns a shell script to the action. I am trying to rewrite it so that instead of accepting a shell script, you can pass in where you want to scroll and by how much. [Here](https://github.com/nikitavoloboev/karabiner-generator/blob/master/karabiner.rb#L178) is the code I have for it so far.

And [here](https://pqrs.org/osx/karabiner/json.html#to-event-definition) is the relevant JSON that needs to be ran to get this to happen. 

It seems this:
`{ "mouse_key": { "vertical_wheel": -64 } }`

Would make it scroll downwards by this -64 value. I call this method [here](https://github.com/nikitavoloboev/karabiner-generator/blob/master/config.rb#L438). This should make me pressing and holding d key and then pressing j to scroll downwards.

However this doesn't happen and I get this error:

```
[2018-08-22 22:40:20.208] [error] [grabber] complex_modifications json error: mouse_key.vertical_wheel should be number: {"vertical_wheel":"-64"}
[2018-08-22 22:40:20.208] [error] [grabber] complex_modifications json error: mouse_key.vertical_wheel should be number: {"vertical_wheel":"-64"}
```

I don't know what I am doing wrong. Would really appreciate any help on this.

Ideally I want to bind my d key + jk keys to scrolling. 

I would also love to get feedback on my Karabiner generator. Am I generating JSON correctly to produce the launcher mode keys? 

cc @tekezo

**Comment by yqrashawn** [comment]
seems your json output needs to be

`{ "mouse_key": { "vertical_wheel": -64 } }`

instead of 

`{ "mouse_key": { "vertical_wheel": "-64" } }`

**Comment by nikitavoloboev** [comment]
Thanks @yqrashawn, you are right.

**Comment by nikitavoloboev** [comment]
One thing I am curious about though is the way I generate the JSON for launcher keys.

For example this code:

```
{
  "description": "comma",
  "manipulators": [
    {
      "type": "basic",
      "from": {
        "key_code": "a",
        "modifiers": {
          "mandatory": [

          ],
          "optional": [
            "any"
          ]
        }
      },
      "to": [
        {
          "shell_command": "osascript -e 'tell application \"Keyboard Maestro Engine\" to do script \"Google clipboard\"'"
        }
      ],
      "conditions": [
        {
          "type": "variable_if",
          "name": "comma",
          "value": 1
        }
      ]
    },
    {
      "type": "basic",
      "from": {
        "simultaneous": [
          {
            "key_code": "comma"
          },
          {
            "key_code": "a"
          }
        ],
        "simultaneous_options": {
          "key_down_order": "strict",
          "key_up_order": "strict_inverse",
          "to_after_key_up": [
            {
              "set_variable": {
                "name": "comma",
                "value": 0
              }
            }
          ]
        },
        "modifiers": {
          "mandatory": [

          ],
          "optional": [
            "any"
          ]
        }
      },
      "to": [
        {
          "set_variable": {
            "name": "comma",
            "value": 1
          }
        },
        {
          "shell_command": "osascript -e 'tell application \"Keyboard Maestro Engine\" to do script \"Google clipboard\"'"
        }
      ],
      "parameters": {
        "basic.simultaneous_threshold_milliseconds": 500
      }
    }
  ]
}
```

Makes it so that pressing comma then pressing a will trigger a KM macro.

But why is there two invocations to call the macro. It seems wrong to me.

**Comment by yqrashawn** [comment]
I think this is what you want. `comma` down into "comma state", `a` down in "comma state" invoke applescript.

You may checked codes like [vi mode](https://github.com/pqrs-org/KE-complex_modifications/blob/master/docs/json/vi_mode.json). I don't know why the code use both simultaneous feature and state feature (`set_variable`), maybe to avoid typo and other unexpected behavior?

I haven't tried the latest rev5 vi mode. I'll try it when I back home.

```
{
  "description": "comma",
  "manipulators": [
    {
      "type": "basic",
      "from": {
        "key_code": "a",
        "modifiers": {
          "optional": [
            "any"
          ]
        }
      },
      "to": [
        {
          "shell_command": "osascript -e 'tell application \"Keyboard Maestro Engine\" to do script \"Google clipboard\"'"
        }
      ],
      "to_after_key_up": [
        {
          "set_variable": {
            "name": "comma",
            "value": 0
          }
        }
      ],
      "conditions": [
        {
          "type": "variable_if",
          "name": "comma",
          "value": 1
        }
      ]
    },
    {
      "type": "basic",
      "from": {
        "key_code": "comma",
        "modifiers": {
          "optional": [
            "any"
          ]
        }
      },
      "to": [
        {
          "set_variable": {
            "name": "comma",
            "value": 1
          }
        }
      ]
    }
  ]
}
```
