### ISSUE TITLE
Conflict with Parallels, Jump Desktop and MS RDP when using PC Style Shortcuts complex modification

### ISSUE THREAD

**Issue by zandhaai** [pqrs-org/KE-complex_modifications#433]
I am so used to the END and HOME buttons to function as 'Goto End/Beginning of current line' so I installed the PC-Style Shortcuts.

Now when using Jump Desktop, Parallels or Microsoft RDP these keys are not behaving normally anymore (inside these applications they were always behaving as 'normal').

My solution is I created 2 profiles: 1 for the Mac (with keys bindings on) and 1 for RDP/Parallels sessions. 

Is there another (more user-friendly) solution?

**Comment by apm1467** [comment]
Which rule in the "PC-Style Shortcuts" are you using?

If your try the rule named "PC-Style Home/End", it should automatically work on Mac and not in Parallels. Does this work for you?

**Comment by zandhaai** [comment]
Oops, I completely missed that other complex modification! I chose the first one 'Home key to the beginning of line' etc.

It works with your suggestion.
