### ISSUE TITLE
Complex Modifications for eject key doesn't work

### ISSUE THREAD

**Issue by ehlers** [pqrs-org/KE-complex_modifications#434]
macOS: 10.13.6
Karabiner Elements: 12.1.0
Mac: iMac mid 2011
Keyboard: Apple Magic Keyboard / Bluetooth

Ctrl-eject Is working fine with Karabiner Elements loaded and EventViewer sees the eject key:
```
eventType:key_down        code:0xb8       name:eject           misc:
eventType:key_up          code:0xb8       name:eject           misc:
```

Simple modifications for the eject key are working as well.

But I can't get complex modifications working for the eject key. Here a basic example:

```
                    {
                        "description": "Test eject key",
                        "manipulators": [
                            {
                                "from": {
                                    "key_code": "eject"
                                },
                                "to": [
                                    {
                                        "key_code": "x"
                                    }
                                ],
                                "type": "basic"
                            }
                        ]
                    }
```

This works fine, when I use another from key_code, but with "eject" it does nothing.

**Comment by apm1467** [comment]
What keyboard are you using? This may be a known limitation of Karabiner Elements.

From https://pqrs.org/osx/karabiner/document.html#features:

> Karabiner-Elements cannot modify `the eject key` on some keyboard (e.g., Apple Wired Keyboard) due to the limitation of macOS API.

**Comment by ehlers** [comment]
It's an Apple Wireless Keyboard from 2009, model A1314, for details see https://en.wikipedia.org/wiki/Apple_Wireless_Keyboard#Third_generation_(A1314)_MC184LL/A_(2_batteries)

What's puzzling me is, that the EventViewer works fine with the eject key, even when using in combination with some modifiers key. So I thought that Karabiner would be able to process that as well.

```
eventType:key_down        code:0xe3       name:left_gui        misc:
eventType:key_down        code:0xb8       name:eject           misc:
eventType:key_up          code:0xb8       name:eject           misc:
eventType:key_up          code:0xe3       name:left_gui        misc:
```

**Comment by ehlers** [comment]
Got it working!!!
Instead of `"key_code": "eject"` I have to use `"consumer_key_code": "eject"`.
