### ISSUE TITLE
Simulating a "sleep" event

### ISSUE THREAD

**Issue by calvinwyoung** [pqrs-org/KE-complex_modifications#443]
I want to implement a rule that maps to a sequence of `to` events, with a slight pause in between each event.

In the older version of Karabiner, I could use `KeyCode::VK_WAIT_100MS` to add a 100ms sleep in between events, but I can't seem to find the functionality in Karabiner-Elements. Does anyone know how to implement this?

Thank you!

**Comment by hailite** [comment]
Need this too. Here is macos. Thanks

**Comment by calvinwyoung** [comment]
Hey all, just following up on this — my current workaround is to insert a bunch of `ESC` keystroke events to simulate a "sleep". This is pretty ugly, but I don't have a better solution at the moment. Hopefully someone else has a less-ugly workaround!
