### ISSUE TITLE
Corded key trigger in vi_mode.json.rb is missing

### ISSUE THREAD

**Issue by masetime** [pqrs-org/KE-complex_modifications#445]
In Karabiner there used to be a way to trigger vi mode by pressing `d` + `s` simultaneously.

I found this method to be superior to the current option of pressing `d` or `s` or another single key to trigger it.

I would restore this functionality to KE myself if I understood how to. I humbly petition for someone with the know-how to restore this option.

**Comment by apm1467** [comment]
You mean this Simultaneous Vi Mode right?

![screenshot 2018-11-29 at 10 06 14](https://user-images.githubusercontent.com/10210967/49210884-807fe000-f3be-11e8-9d0c-fc630f988f0e.png)
