### ISSUE TITLE
Remap delete key to go to previous folder / Fn+delete key to move to trash / F2 to rename files

### ISSUE THREAD

**Issue by ssw112** [pqrs-org/KE-complex_modifications#450]
Hi! I just found the rule that allows to open files/folders with return key, so I'd like to know if it's possible to add rules mentioned in the title to make it more convenient if you work simultaneously on mac and windows.

Thanks!

**Comment by Jendker** [comment]
Sure it's possible. You would just need a profile which will work only in Finder. If you cannot find the needed rule just add it yourself (https://pqrs.org/osx/karabiner/json.html) and make pull request so that everyone can benefit from it.
