### ISSUE TITLE
Add url to the website on description section on this repo

### ISSUE THREAD

**Issue by ryuheechul** [pqrs-org/KE-complex_modifications#455]
I think that will make it easier to access this page, https://pqrs.org/osx/karabiner/complex_modifications/ easily via this repo

**Comment by apm1467** [comment]
Do you mean add the url https://pqrs.org/osx/karabiner/complex_modifications/ to the README file of this repo? Isn't the url already in the README file?

**Comment by ryuheechul** [comment]
Yup, I know the link is ine the README.md

But I meant in the repo

you can click edit button on the repo's home like in the picture below
![screen shot 2018-11-29 at 8 07 34 pm](https://user-images.githubusercontent.com/2637709/49218014-9dde9980-f412-11e8-9cf0-bd9e69fe178f.png)

then there is a website text box in the picture below you can add the URL
![screen shot 2018-11-29 at 8 07 44 pm](https://user-images.githubusercontent.com/2637709/49218013-9d460300-f412-11e8-8e5a-edbdf024a1c7.png)

the URL should be there for anyone can click to go to the website without scrolling down to read the README.md
![screen shot 2018-11-29 at 8 08 21 pm](https://user-images.githubusercontent.com/2637709/49218012-9cad6c80-f412-11e8-912b-1d155dfd6813.png)

**Comment by ryuheechul** [comment]
I just think it will be better than showing the message  _"No description, website, or topics provided."_

**Comment by ryuheechul** [comment]
Hope a someone has the permission to do this can consider this issue!

**Comment by suliveevil** [comment]
Maybe only tekezo can add a description to this repo.

**Comment by tekezo** [comment]
Thank you for feedback!
I updated the description.
