### ISSUE TITLE
Programmer Dvorak Layout

### ISSUE THREAD

**Issue by bradywatkins-ooh-n** [pqrs-org/KE-complex_modifications#469]
Hi, I noticed in #366 Programmer Dvorak with QWERTY Commands rev2 was introduced. I was wondering if there are any plans to release Programmer Dvorak by itself @apm1467 ?

**Comment by bradywatkins-ooh-n** [comment]
@AlexeyPopov would you have a copy of this?

**Comment by AlexeyPopov** [comment]
@bradywatkins-ooh-n We can't completely fix this issue. You can try current version with #366 fix.

**Comment by bradywatkins-ooh-n** [comment]
Thanks for the reply @AlexeyPopov. Actually my query was not whether the problem was fixed, rather I was wondering if you have/could generate a copy of Programmer Dvorak *without* command QWERTY?

**Comment by bradywatkins-ooh-n** [comment]
any update on this? I would greatly appreciate it if you have the layout.

**Comment by AlexeyPopov** [comment]
I think author of #366 can help you.

**Comment by bradywatkins-ooh-n** [comment]
@apm1467 do you have the source code for Programmer Dvorak *without* CMD-QWERTY?
