### ISSUE TITLE
Condition checking if USB keyboard plugged in

### ISSUE THREAD

**Issue by trandoanhung1991** [pqrs-org/KE-complex_modifications#48]
In KE there's an option to disable built-in keyboard when a USB keyboard is attached. What I would like to do is to be able to use this detection to do a key swap. Is such a condition supported?

**Comment by Huluk** [comment]
I would love this as well! Sadly, this is not something a KE-complex_modification can do, this change needs to happen in the main part of Karabiner-Elements.
