### ISSUE TITLE
Use shift to select text in Vi mode

### ISSUE THREAD

**Issue by volt4ire** [pqrs-org/KE-complex_modifications#49]
Is there a way to have the Vi mode complex modifiers be used to select text while shift is held down? For example, I would love to be able to press ⌃+⇧+h to select the character to the left, like pressing shift and the left arrow key does. Being able to hold ⇧+⌥+h to select all the preceding characters in the current word and ⇧+fn+h to select the preceding characters in the paragraph like ⇧+⌥+← and ⇧+fn+← do respectively would make this even better. Thanks!

**Comment by apm1467** [comment]
That's an interesting idea. I've done it by simulating the virtual mode in vim. You can check the new version of Vi Mode now.

**Comment by volt4ire** [comment]
Thanks for the quick update! I can't seem to get the Vi Mode rev 4.1 to select text, however. When I press the trigger key (⌃) +⇧+h/j/k/l to select text, nothing happens. Am I invoking the trigger incorrectly?

**Comment by apm1467** [comment]
The trigger key is either S or D depending on the rule you choose. There's no control or shift involved. 

Just press S + V + H or D + V + H to see the result.
