### ISSUE TITLE
 Keypad as Arrows (windows style) does not input "key_code": "keypad_7"

### ISSUE THREAD

**Issue by bunmirfak** [pqrs-org/KE-complex_modifications#511]
When NumLock is on, I can't enter keypad_7.

 Before line 68  "type": "basic" something is missing. 

Compared other key, I think the missing lines may be as follows.

          "conditions": [
            {
              "type": "variable_unless",
              "name": "Num Lock",
              "value": 1
            }
          ],

**Comment by imasaru** [comment]
@bunmirfak Hey there! I didn't see your issue, but I pushed this fix to `numpad.js` yesterday. Thanks!
