### ISSUE TITLE
Is it possible to make one key press fire a sequence of keys?

### ISSUE THREAD

**Issue by jefferickson** [pqrs-org/KE-complex_modifications#530]
I would like to make my `right_command` key fire off `CTRL+A` followed by `H`. Is this possible with complex modifications? I haven't been able to find an example of a mod like this.

Thank you!
Jeff

**Comment by mingaldrichgan** [comment]
Multiple `"to"` events do appear to be supported, e.g.
https://github.com/mingaldrichgan/KE-complex_modifications/blob/master/docs/json/personal_tekezo.json#L723-L745

**Comment by jefferickson** [comment]
Perfect, thank you @mingaldrichgan !
