### ISSUE TITLE
LeftCtrl+F1...F12 as Fn+F1...F12?

### ISSUE THREAD

**Issue by for-coursera** [pqrs-org/KE-complex_modifications#536]
Hi!

I remapped my `Fn` key to `LeftControl` (I'm too used to it being the leftmost key), but is it also possible to make it still act as `Fn` if pressed with the function keys F1...F12?

Thank you.

**Comment by sfrvtma** [comment]
Make Left Control a mandatory modifier for F1-12 and add the Fn key in output
