### ISSUE TITLE
"Hyper" key on keyboard in combination with Mouse Button events

### ISSUE THREAD

**Issue by haakonstorm** [pqrs-org/KE-complex_modifications#537]
# Hyper + mousebuttons for misc:flags: right_alt,right_control,right_gui,right_shift 

- Remap `caps-lock` to `right-cmd`+`right+option+`right-shift`+`ctrl` to avvoid collision with other applications
- Use `caps-lock` as a `hyper` key in combination with other keys
- Want to assign `hyper` + `mouse button1`, as well as `hyper` + `mouse button2` (...)
- Is this possible?
- In order for this to be useful to other customization programs, possible to remap all combinations automatically, e.g.:
  - make new single button and everything is sent there including `misc:flags: right_alt,right_control,right_gui,right_shift`:
    - hyper+button1 --> button6
    - shift+hyper+button1 --> button6 {misc:flags: right_shift,right_control,right_gui,right_shift }
    - alt+hyper+button1, cmd+hyper+button1, ctrl+hyper+button1, alt+cmd+hyper+button1...
    - alt+hyper+button2, cmd+hyper+button2, ctrl+hyper+button2 ...
  - or perhaps sequentially to make it easier for other applications:
    - hyper+button1 --> button6
    - shift+hyper+button1 --> button7
    - cmd+hyper+button1 --> button8
    - cmd+option+hyper+button1 --> button9
    - (...)
    - hyper+button2 --> button15
    - shift+hyper+button2 --> button16
    - (...)

## Karabiner-eventviewer output

```
type:key_down        code:231        name:right_gui       misc:flags: right_gui 
type:key_down        code:228        name:right_control   misc:flags: right_control,right_gui 
type:key_down        code:230        name:right_alt       misc:flags: right_alt,right_control,right_gui 
type:key_down        code:229        name:right_shift     misc:flags: right_alt,right_control,right_gui,right_shift 
type:button_down     code:0          name:button1         misc:{x:807,y:109} click_count:1 flags:shift,ctrl,opt,cmd
type:button_up       code:0          name:button1         misc:{x:807,y:109} click_count:1 flags:shift,ctrl,opt,cmd
type:key_up          code:229        name:right_shift     misc:flags: right_alt,right_control,right_gui 
type:key_up          code:228        name:right_control   misc:flags: right_alt,right_gui 
type:key_up          code:230        name:right_alt       misc:flags: right_gui 
type:key_up          code:231        name:right_gui       misc:
```

## Karabiner HYPER KEY MODE

An easy way to work with HYPER key, so that HYPER can be used in configuration just by using the name `hyper` just like `name:right_control` but with `name:hyper`

**Comment by donniebreve** [comment]
I believe this belongs in the [Karabiner Elements](https://github.com/pqrs-org/Karabiner-Elements/) repo.
