### ISSUE TITLE
PC-Style Home/End not always working in non-English keyboard layout

### ISSUE THREAD

**Issue by aaksyonenko** [pqrs-org/KE-complex_modifications#542]
macOS version: macOS 10.14.6
Karabiner version: Karabiner-Elements 12.7.0
Your Mac hardware: MacBook Pro
Your keyboard hardware: Das Keyboard 4 Professional for Mac Mechanical Keyboard

When changing from English to Russian keyboard layout, in some apps (Safari, Chrome, perhaps others) the Home and End keys do nothing.  In English layout - they work fine with the modifier in those apps.  In TextEdit the keys work fine in either layout with the modifier.  The Event Viewer shows the same codes being sent from the keyboard in either layout.  What could be the cause of this, and how can this be fixed?

**Comment by donniebreve** [comment]
I noticed something similar, home and end work normally in VSCodium but not in Firefox. I was using the TouchCursor Mode modification.

I believe this is just something weird on macOS. The behavior you want comes from command + left/right on macOS. I would suggest remapping home and end to command + left/right. When I changed touchcursor to these, “home” and “end”, seemed to work in most applications.

Home/end/command+left/right still will not work properly in terminal, and I am not sure what the best route is for that.

**Comment by aaksyonenko** [comment]
I guess I'll have to look into TouchCursor... I went as far as modifying the "DefaultKeyBinding.Dict" manually, but that gives really screwed up results.  See attachment (added the ".txt" so I can attach here).  Home and End changes work fine, Shift+Home/End work fine.  But only in English.  If I switch input language - they still do nothing.  
In any language input, English or otherwise:
Ctrl+Shift+Home/End don't work at all.  Ctrl+Shift+Left arrow properly selects word by word, but Ctrl+Shift+Right arrow simply moves the cursor without selecting.  I can't figure out any rhyme or reason for why this is behaving the way it does, I checked all the commands and they seem to be correct.
[DefaultKeyBinding.Dict.txt](https://github.com/pqrs-org/KE-complex_modifications/files/3778856/DefaultKeyBinding.Dict.txt)

**Comment by aaksyonenko** [comment]
Ok, I think this fixed the issue.  I do not have push rights to the repository, so I will upload the file here, in the hopes that someone finds it and uploads it, if necessary.

This JSON contains character-independent modifications.  Warning - they may screw up some of the built-in OS functionality (such as switching desktops by using Ctrl+Right arrow won't work anymore).

The PC-Style Home/End uses Cmd+[arrow] mappings to make it behave exactly as in Windows, including Shift and/or Ctrl modifiers (end of page, start of page as well as end/start of line).

The PC-style Left/Right also uses Cmd+[arrow], but with the required Ctrl modifier, to enable skipping and/or selecting left and right word by word.

These modifications should work with any input language keyboard layout, because they do not use any language-specific characters, only the control keys.

[personal_aaksyonenko_pc_style_home_end_arrows_multilingual.txt](https://github.com/pqrs-org/KE-complex_modifications/files/3779496/personal_aaksyonenko_pc_style_home_end_arrows_multilingual.txt)
