### ISSUE TITLE
Swap Ctrl-Command disables shift selection in text

### ISSUE THREAD

**Issue by ATAjosh** [pqrs-org/KE-complex_modifications#543]
Normally (and in older versions of Karabiner - such as 12.1) you can click in text, then hold shift and click somewhere else to select everything in between.

With "PC Style" Swap Ctrl-Command, on the latest version of Karabiner this functionality gets disabled on external keyboards.

**Comment by Nes-si** [comment]
I've accepted the issue. Please, open it. 
For something reason, the modification contains Shift processing:
```
{
          "type": "basic",
          "from": {
            "key_code": "left_shift",
            "modifiers": {
              "optional": [
                "any"
              ]
            }
          },
          "to": [
            {
              "key_code": "left_shift",
              "lazy": true
            }
          ]
        },
```
(and the same for the right shift)
I've removed it and the issue was gone. 
What was it?
