### ISSUE TITLE
Neo2 - Layer3 not working in VirtualBox

### ISSUE THREAD

**Issue by Zornell** [pqrs-org/KE-complex_modifications#548]
Hi there,
i am currently trying to figure out why Layer3 is not working in my VirtualBox Guest.
When tab is pressed and any other key is used the behaviour is the same as if a layer 4 key is pressed.

Here is my setup:
OSX 10.14.6
Karabiner 12.7.0, Complex Modifications: Neo2
VirtualBox 6.0.12, Host Key: right ctrl
Guest OS: CentOS 7, Xfce, Keyboard Layout neo2

The issue is the same when using a rdp connection. And yes i know not many people have this kind of problem. Still, any help is highly appreciated!

**Comment by jgosmann** [comment]
Remote desktop and virtualization solutions will probably always be problematic and there is likely no solution that works for everyone. I rarely use VirtualBox, but when I do, I switch my Karabiner config to one where only activation of caps lock with both shift keys is enabled (you can specify multiple sets complex rules and switch between them through the menu bar icon). In the guest OS I would install the Neo2 layout and have it handle everything. Of course not the best solution if you switch between the host and guest OS a lot.

I think you can use a complex modification to map to two simultaneous modifier key presses (not sure about non-modifiers) or two key presses in sequence. However, I suppose you only want one of those key presses depending on whether you are in the host or guest system and the other key press will mess with things in unexpected ways.

I don't think it is possible to do a full layer 3 implementation just with Karabiner, but it might be possible for the most essential characters.

**Comment by Zornell** [comment]
Thank you very much for your thoughts!
Using two modifiers might work. Sending two keycodes for one keystroke is not working. The keycode in the to event is exclusive. For now i will stay with my work around. Switching between two sets of complex rules would also be okay for me. If i get a shortcut for this working, i will share it here.

**Comment by Zornell** [comment]
Here my rules to switch between my Neo2 and Neo2_VBox Profile by pressing cmd+Esc. One rule for each profile.

https://gist.github.com/Zornell/a73c4743e50bdd57ffd38e0b55821c7a
