### ISSUE TITLE
My personal complex mod isn't being recognised

### ISSUE THREAD

**Issue by sfrvtma** [pqrs-org/KE-complex_modifications#560]
I've checked everything and cannot find what's wrong, please help me

https://www.mediafire.com/file/2kr7uojmepti21a/textmanishort.json/file

**Comment by tekezo** [comment]
karabiner_cli linter helps you.

You can use linter from Terminal.app by the following command. 
(Replace `~/Downloads/textmanishort.json` with yours.)

```shell
$ '/Library/Application Support/org.pqrs/Karabiner-Elements/bin/karabiner_cli' --lint-complex-modifications ~/Downloads/textmanishort.json

[json.exception.parse_error.101] parse error at line 20, column 27: syntax error while parsing object - unexpected string literal; expected '}'
```

**Comment by sfrvtma** [comment]
I still don't understand the problem. Line 20:27 shouldn't have `}` in it, and column 27 is actually the end of a string; maybe I am completely wrong about this, this is maybe my first time using JSON

**Comment by sfrvtma** [comment]
Okay solved, needed to replace dome of the `{}` with `[]`
