### ISSUE TITLE
Complex Modification not Working - remapping Excel CTRL-U

### ISSUE THREAD

**Issue by yoktan** [pqrs-org/KE-complex_modifications#567]
Hi,

I'm having a hard time swapping CTRL-E for CTRL-U in Excel. I've saved the following JSON in ~/.config/karabiner/assets/complex_modifications/

```
{
  "title": "Excel - CTRL-U (edit cell) to CTRL-E",
  "rules": [
    {
      "description": "Edit cell with CTRL-E",
      "manipulators": [
        {
          "type": "basic",
          "from": {
            "key_code": "u"
            "modifiers": {
              "mandatory": ["control"]
            }
          },
          "to": {
            "key_code": "e"
            "modifiers": {
              "mandatory": ["control"]
            }
          },
          "conditions": [
            {
              "type": "frontmost_application_if",
              "bundle_identifiers": [
                "^com\\.microsoft\\.Excel"
              ]
            }
          ]
        }
      ]
    }
  ]
}
```
I've also tried a variation of the above with ^com.microsoft.Excel asa the bundle identifier. Still fails.

**Comment by tekezo** [comment]
Your rule changes CTRL-U.
You have to exchange "u" and "e" in your json.

**Comment by yoktan** [comment]
> Your rule changes CTRL-U.
> You have to exchange "u" and "e" in your json.

Thank you, but I had already tested the reverse and that still fails… 
By the way, I'm assuming that every time I make an update it is enough to restart Karabiner-Elements and the relevant app (in this case Excel).
