### ISSUE TITLE
How to transfer my Karabiner elements settings to a new computer

### ISSUE THREAD

**Issue by garbage914** [pqrs-org/KE-complex_modifications#572]
Hello, a year or two ago, I was able to write a script (with some online help) that lets my command and control key be swapped but only when using Teamviewer (I control a PC when using Teamviewer). The modifications work great. I'm upgrading to a new computer. Can someone tell me where I can find those scripts and transfer them? I see them under the "Complex Modifications" tab but don't know how to look at them in Karabiner or how to export all settings. I just realized that if I hit "Show package Contents," there is a script called "simple_modifications.json" in the Resources folder. Do I just need to copy that?

**Comment by tekezo** [comment]
Karabiner-Elements configuration file is stored at `~/.config/karabiner`.
Please follow the instruction to transfer your configuration.

1. Open Terminal app.
2. Execute `open ~/.config` on Terminal, then Finder will show the config folder.
3. Copy `karabiner` folder to new computer's  config folder, then your configuration will be restored.

**Comment by garbage914** [comment]
Excellent - that does it.  Thanks so much @tekezo

**Comment by sarnobat** [comment]
Copying the dotfiles doesn't do anything for me.

**Comment by sarnobat** [comment]
Strange, mine imports the mappings but doesn't have any effect on the physical keypresses in my external keyboard.
