### ISSUE TITLE
Config Generator

### ISSUE THREAD

**Issue by mikelxc** [pqrs-org/KE-complex_modifications#585]
It would be nice to have an online complex modifications generator that can generate JSON files based on users' settings so that they can create & import it directly from web.

**Comment by jhelvy** [comment]
I suspect this will be quite difficult to build, but there are existing tools that can dramatically simplify the process of creating the JSON file for complex modifications. For example, check out GokuRakuJoudo: https://github.com/yqrashawn/GokuRakuJoudo

**Comment by jimpsson** [comment]
I have thought of doing exactly this using mainly Vue.js as the frontend framework, if someone would like to create a project together, then I'm interested in putting in some of my time to actually create this, it's totally possible and ideas is nothing I lack, just don't want to create something like this alone...

**Comment by mikelxc** [comment]
Cool, maybe we can do it together

**Comment by genesy** [comment]
I made one today but it's unfinished if you guys want to check it out https://genesy.github.io/karabiner-complex-rules-generator/
