### ISSUE TITLE
Gesture sliding

### ISSUE THREAD

**Issue by hwtl** [pqrs-org/KE-complex_modifications#59]
Looking for a touchpad application between the sliding function
In full-screen display between the sweep

**Comment by tekezo** [comment]
Gesture events is not target of Karabiner-Elements.
Please use another apps.

**Comment by kamykaze** [comment]
I'm not clear what you're looking for. An application to customize trackpad gestures?

Anyways, Karabiner Elements is for remapping keyboard keys only. I think you're looking for something like [BetterTouchTool](https://www.boastr.net/)
