### ISSUE TITLE
Right Option Key to Enter (not return)

### ISSUE THREAD

**Issue by PeterWagemans** [pqrs-org/KE-complex_modifications#603]
I am quite used to use the right option key as an Enter key, I use it a lot in FileMaker dialogs. This because historically, on MacBooks, there used to be an enter key there instead of an option key.
Until now, Karabiner has been able to solve this problem for me by mapping right option to num keypad enter. On my new MacBook 16" with Catalina, this is not working anymore.

Is there any way I can get this to work again? Thanks!

**Comment by tekezo** [comment]
Karabiner-Elements provides `keypad_enter` which you can find in Simple Modifications key list.

**Comment by PeterWagemans** [comment]
Yes, but this not working anymore.

**Comment by PeterWagemans** [comment]
I have to correct myself. It is working now. Apparently redefining it, solved the problem. Or I was not paying attention. Sorry :-)
