### ISSUE TITLE
'Disable Ctrl Click' Modification not working

### ISSUE THREAD

**Issue by hth2** [pqrs-org/KE-complex_modifications#615]
I apologize if this has been already resolved elsewhere. 

I would like to disable Ctrl Left Click. After some googling it seems the solution is to install Karabiner-Elements  and import the complex modification "Ctrl + Left Click to Left Click". However it seems to have no effect. How can I debug why it is not working as expected?

macOS version: macOS 10.12.6
Karabiner version: Karabiner-Elements 12.8.0
Mac hardware: iMac (Retina 5K, 27-inch, Late 2015)
Keyboard hardware: Cherry G230 USB wired keyboard

**Comment by tekezo** [comment]
You have to choose your mouse on Devices tab.
https://pqrs.org/osx/karabiner/document.html#configuration-devices

**Comment by hth2** [comment]
yes it helped, many thanks for the quick response!

**Comment by NicholasJBond** [comment]
https://karabiner-elements.pqrs.org/docs/manual/configuration/configure-devices/

Old link doesn't work. I've posted the link that works for me
