### ISSUE TITLE
Vortex Pok3er Media Controls not for Vortex Core?

### ISSUE THREAD

**Issue by h-nn-ng** [pqrs-org/KE-complex_modifications#64]
Hoped that the Media Keys for the Pok3r would also work with the Vortex Core (some manufacturer etc.) which isn't the case. Is this intended and might a small change activate my beloved media keys on my Core again?

**Comment by stoasome** [comment]
The complex modifications work on operating system level. Media keys directly on a keyboard should still work as the commands are sent directly from the keyboard.
That means these complex modifications overwrite just the key-combination Caps Lock + QWE / SDF.

Currently i'm using a different programmable keyboard with media keys bound to the same combination, and my media controls work just fine. I cannot reproduce any problem.

The pok3r media controls rules are intended to use them on a non-pok3r keyboard, that does not support that key combination.
