### ISSUE TITLE
Disable NonBreaking Space

### ISSUE THREAD

**Issue by lichtamberg** [pqrs-org/KE-complex_modifications#67]
Pleaseeeee https://github.com/tekezo/Karabiner-Elements/issues/412

**Comment by kamykaze** [comment]
We need more details on what the mapping/functionality for this is. The old Karabiner had a lot of mappings.

**Comment by lichtamberg** [comment]
I dont know, there was only a option then.. But maybe the old mapping helps? https://superuser.com/questions/78245/how-to-disable-the-option-space-key-combination-for-non-breaking-spaces/479358#479358

**Comment by kamykaze** [comment]
Basically this is a mapping for

Alt+Space -> Space
Alt+Shift+Space -> Space

I'll work on this.

**Comment by lichtamberg** [comment]
thank you very much!

**Comment by kamykaze** [comment]
This was added to a new pull request #71 .  

Please copy the content of the [docs/json/nonbreaking_space.json](https://github.com/kamykaze/KE-complex_modifications/blob/9e97963658489af7ccaeb99cc0038d385c69e6ea/docs/json/nonbreaking_space.json) to ~/.config/karabiner/assets/complex_modifications/nonbreaking_space.json to test it. 

I do not have the same issue in iTerm, but I was able to confirm the mapping should work via KE's event viewer.

**Comment by kamykaze** [comment]
This has been merged. You can simply use the import from web functionality now. 

Closing this.

**Comment by lichtamberg** [comment]
Works, thank you very much!
