### ISSUE TITLE
Omit specified apps from complex modifications or KE as a whole?

### ISSUE THREAD

**Issue by pthieu** [pqrs-org/KE-complex_modifications#7]
I have simple modifications working to swap `fn` and `left_control`, and then I have complex modifications to change `left_control` to `left_command` in some situations like `left_control + c` (trying to emulate windows).

In the old Karabiner, these rules omitted the terminal app because `ctrl + c` was required to break out of a running process, now these key swaps are OS wide. Any way to omit the `Terminal.app`?

**Comment by tekezo** [comment]
I'm working for this application specific rules.
Please wait for a while.

**Comment by pthieu** [comment]
Any idea how long? Do you need any help? I've been looking to contribute to KE.

**Comment by pthieu** [comment]
@tekezo Any idea how long? Do you need any help? I've been looking to contribute to KE.

**Comment by tekezo** [comment]
I've added this feature at 0.91.6. (`frontmost_application_if` and `frontmost_application_unless`)

An example json:
https://github.com/pqrs-org/KE-complex_modifications/blob/master/docs/json/emacs_key_bindings.json

A source file of the json:
https://github.com/pqrs-org/KE-complex_modifications/blob/master/src/json/emacs_key_bindings.json.erb

**Comment by pthieu** [comment]
LGTM. Thanks.
