### ISSUE TITLE
Can't import rules, Ultimate macOS

### ISSUE THREAD

**Issue by XIYO** [pqrs-org/KE-complex_modifications#716]
MacMini, 2012 Late
macOS, Catalina 10.15.5
Karabiner-Elements, 12.10.0

My native language is Korean.
So I used Google Translator.
Please understand even if the words are strange.

I always use it with gratitude.

I use karabiner's ultimate macOS rule.

1. I left my Mac for a few days.
2. With the power off, connect a 2.4ghz USB type receiver. (Because Mac mini cannot boot without a keyboard and mouse connected.)
3. You are back today.

Karabiner is now unable to find the Ultimate macOS rule and cannot add it.
Other rules can still be added.

To solve this problem
1.It was deleted and reinstalled with karabiner uninstaller. Still having problems
2. I also deleted User files from https://karabiner-elements.pqrs.org/docs/help/advanced-topics/installed-files/.
(First, after deleting the karabiner, and then deleting the user files, and reinstalling)

Still I can't add Ultimate macOS.

Any help would be greatly appreciated.

**Comment by harmtemolder** [comment]
Do you mean that if you go to https://ke-complex-modifications.pqrs.org/#ultimate_macOS and click `Import`, nothing happens?

**Comment by XIYO** [comment]
Yes I can't import that ultimate macOS rule

**Comment by MuhammedZakir** [comment]
It is because of the first rule.

```
        {
            "description": "ultimate macOS (version: 1556140182)"
        },
```

It is probably because there is no `manipulators` in it. You can fix it by either removing that rule or adding `manipulators`.

```
        {
            "description": "ultimate macOS (version: 1556140182)",
            "manipulators": [{}]
        },
```

**Comment by XIYO** [comment]
@MuhammedZakir thank you sir.
but I steel have can't import ultimate macOS rules

**Comment by XIYO** [comment]
oh... it is not working
