### ISSUE TITLE
Map request: « caps lock moves numbers and symbols to middle rows »

### ISSUE THREAD

**Issue by AntoineBalaine** [pqrs-org/KE-complex_modifications#726]
Hello, 
I’m clueless with programming, can anyone help me put together this map ? 
The idea is: when holding caps lock, the before-to-last row turns into numbers, and the middle row turns into symbols ( "«»()@+-/*=% ).
I’m thinking this could be a good option for minimizing movement on the keyboard and maintain good accuracy. 

Thanks in advance!

**Comment by harmtemolder** [comment]
@AntoineBalaine Do you mean that when holding caps lock:
- A = «
- S = »
- D = (
...
- Z = 1
- X = 2
- C = 3
...
?

**Comment by AntoineBalaine** [comment]
Yes, exactly !

**Comment by harmtemolder** [comment]
In that case you might be interested in this mod: https://github.com/pqrs-org/KE-complex_modifications/blob/master/public/json/caps_tenkey_mode.json. It's not exactly what you want, but a good starting point:
- Pressing caps lock enables it, pressing it again disables. Change that to a combination of [`to_if_held_down`](https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/to-if-held-down/) and [`to_after_key_up`](https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/to-after-key-up/) for holding.
- It maps M = 1, comma = 2, period = 3, etc. That should not be too hard to change to what you want. You can use the EventViewer to see what the names of the keys for your special characters (“«”) are by typing them on your keyboard

**Comment by AntoineBalaine** [comment]
Wonderful, thank you very much !

**Comment by AntoineBalaine** [comment]
This is what I got so far for the "tenkey enable", but it's not working:

`	{
		"description": "CAPS Tenkey: TenkeyMode on/off toggle",

		"manipulators": [
			{
				"type": "basic",
				"from": {
					"key_code": "caps_lock",
					"modifiers": {-} #this is folded
				},
				"parameters": {
					"basic.to_if_alone_timeout_milliseconds": 250,
					"basic.to_if_held_down_threshold_milliseconds": 250
				},
				"to_after_key_up": [
					{
						"set_variable": {
							"name": "tenkey_mode",
							"value": 0
						}
					}
				],
				"to_if_held_down": [
						{
						"set_variable": {
							"name": "tenkey_mode",
							"value": 1
						}
					}
				]
			}
		]
	}
`

What am I getting wrong ?

**Comment by harmtemolder** [comment]
I added

```json
{
  "title": "Test for AntoineBalaine",
  "maintainers": [
    "AntoineBalaine"
  ],
  "rules": [
```

around your code and added in Karabiner. It works for me:

[Screenshot-2020-08-01-at-15-41-23.png](https://postimg.cc/8JbLSBSQ)

(Notice the `tenkey_mode` variable set to `1`)

**Comment by AntoineBalaine** [comment]
Thanks for your help !
