### ISSUE TITLE
How to prevent option+i on mac resulting in ˆ?

### ISSUE THREAD

**Issue by st-schneider** [pqrs-org/KE-complex_modifications#733]
Is there a way to take option+i as a shortcut instead of ˆ? Maybe this is a none-deadkeys deadkeys thing?

**Comment by harmtemolder** [comment]
You should be able to map it to anything you want through [a complex modification](https://karabiner-elements.pqrs.org/docs/json/typical-complex-modifications-examples/). To what do you want to set the shortcut?

**Comment by bm-stschneider** [comment]
well, to not being a dead key and only be option+i.

**Comment by MuhammedZakir** [comment]
Where do you get `^?`when pressing option+i?

**Comment by bm-stschneider** [comment]
Well everywhere with the U.S. keyboard layout

**Comment by bm-stschneider** [comment]
Well, how do I modify it with KE then? It is a combination of two keys and the simple modifications only give me option for one.

**Comment by MuhammedZakir** [comment]
After thinking about it, I would do it in two ways depending on my use case -

1. If I don't need shortcuts using `option` and special characters at the same time.
    * Add `U.S.` and `ABC` in `System Preferences > Keyboard > Input Sources` and enable input menu bar; so that I can switch between them easily.
2. If I need them both, then I will use `ABC` input source and modify it.
    * I will use `Fn` as modifier key for these characters because it is the safest option; all the others are usually used as shortcut keys. You can use `option`, `command` or `control` as long you use keys which do not conflict with shortcut keys of the apps you use.

> Well, how do I modify it with KE then? It is a combination of two keys and the simple modifications only give me option for one.

You use complex modifications [1] as mentioned above. An example modification can be found here -- https://github.com/pqrs-org/KE-complex_modifications/issues/697#issuecomment-674435727.

[1] https://karabiner-elements.pqrs.org/docs/json/typical-complex-modifications-examples/
