### ISSUE TITLE
frontmost_application_if does not work for Paste app.

### ISSUE THREAD

**Issue by Alex-k-tech** [pqrs-org/KE-complex_modifications#734]
The Paste app https://pasteapp.io/

the `frontmost_application_if` does not work because the Past app does not have a focus when it shows.
Any ideas on how I can override key for Paste app?

![image](https://user-images.githubusercontent.com/54838534/90640759-1154ba00-e239-11ea-9490-e5ede386d5b8.png)

**Comment by MuhammedZakir** [comment]
Can you please provide more details about what exactly you want to achieve? Usually, if you want to override keys for apps which are not detected, you use conditions and/or simultaneous keys. See https://github.com/yqrashawn/GokuRakuJoudo/blob/master/tutorial.md#simlayers - a brief description and 2 examples.
