### ISSUE TITLE
I added a rule to swap cmd/ctrl for vncviewer/RDM/Parallels only, and now my keyboard modifier settings fail

### ISSUE THREAD

**Issue by alecazam** [pqrs-org/KE-complex_modifications#738]
I normally have the ctrl/cmd keys swapped on my Mac, since I have to work with Windows and Mac on a daily basis.  I've used Karabiner in the past to define an xml file to swap these for apps that swap them back (RDM/Parallels).  I just updated to KE, and I found and added "complex action: called "Swap Ctrl/CMD" that only when installed said it was specific to vncviewer.   I then removed the item, since I thought I might be able to edit from that starting script.

But now my System preferences modifier key swap doesn't work anymore after adding/removing that.  I even disabled KE, and removed it from the startup items.  This is rather distressing, since I rely on this system mapping to use my keyboard.  I just hear the "bonk" sound trying to hit crtl+C on my macOS apps which used to work.

**Comment by MuhammedZakir** [comment]
Open EventViewer [1] and post here what do you get when you press `control` and `command`.

[1] Karabiner-EventViewer.app or `KarabinerElements menu > Launch EventViewer`
