### ISSUE TITLE
Unable to import custom rules from .json in /.../karabiner/assets/complex_modifications

### ISSUE THREAD

**Issue by Dylan-Bollard** [pqrs-org/KE-complex_modifications#757]
To whom it may concern,

I'm working on a custom list of modifications that I plan to fork at some point, but want to make sure they work independently . I'm trying to import rules using these instructions: https://karabiner-elements.pqrs.org/docs/json/root-data-structure/ about a custom *.json files. I can't see the complex modifications in the UI for Karabiner Elements under "Complex modifications". 

So far, the only way to include a complex modification was pasting them into the main config file. But I'd like to create a stand a lone file that can be pulled form my GitHub. Is my code wrong? I included a specific example. Did I put it in the wrong place? /.../.config/karabiner/assets/complex_modifications 

Thank you for helping and your clarification. 

~~~~~~~~~~
{
    "title": "Complex Modifications."
    "rules": [
        {
            "description": "right enter to command + enter",
            "manipulators": [
                {
                    "from": {
                        "key_code": "keypad_enter"
                    },
                    "to": [
                        {
                            "key_code": "3",
                            "modifiers": [
                                "left_command",
                                "return_or_enter"
                            ]
                        }
                    ],
                    "type": "basic"
                }
            ]
        }
    ]

}

~~~~~~~~~~

**Comment by MuhammedZakir** [comment]
```json
{
    "title": "Complex Modifications."
   ...
```

You missed a comma at the end.

```
{
    "title": "Complex Modifications.",
   ...
```
