### ISSUE TITLE
Sticky key

### ISSUE THREAD

**Issue by bolshakov** [pqrs-org/KE-complex_modifications#76]
Hello, I wonder if it's possible to configure kind of sticky key. For example, I wan't to press F13, release it and treat any key pressed after F13 release in a special way.

Thus, I can press two keys each after another, not simultaneously.

In the classic Karabiner era I used the following config for that purpose:

```xml
  <item>
    <name>Command Mode</name>
    <appendix>Enable by pressing F13</appendix>
    <identifier>private.command_mode</identifier>

    <autogen>__KeyToKey__
      KeyCode::F13, KeyCode::VK_STICKY_COMMAND_MODE
    </autogen>
  </item>
```

Is it possible to achieve the same behaviour with Karabiner Elements?

**Comment by apm1467** [comment]
This is possible. I can describe a solution here:

Press F13 to set a variable to 1, if the current value of that variable is 0; and set that variable to 0, if the current value is 1.

So every time you press F13, you just change the mode.
