### ISSUE TITLE
steel ultimate macOS can't import

### ISSUE THREAD

**Issue by XIYO** [pqrs-org/KE-complex_modifications#764]
I read it 'fixed ultimate MacOS' rule.
but it steel was can't not import.

I was copy new 'ultimate macOS' json ~/.config/karabiner/assets/complex_modifications
and also another rules copy
but  another rules is added.
just not added 'ultimate macOS'

It is because of the first rule.

```
        {
            "description": "ultimate macOS (version: 1556140182)"
        },
```

You can fix it by either removing that rule or adding `manipulators`.

```
        {
            "description": "ultimate macOS (version: 1556140182)",
            "manipulators": [{}]
        },
```

P.S. I am not sure whether `manipulators` is needed for every rules, even for empty ones, or if this is just a bug in KE.

Edit: It looks like `manipulators` is a must from KE 12.10.0. See https://github.com/suliveevil/Capslock/pull/2.

_Originally posted by @MuhammedZakir in https://github.com/pqrs-org/KE-complex_modifications/issues/716#issuecomment-708920766_

**Comment by MuhammedZakir** [comment]
It's working for me! I am using Kararbiner-Elements 12.10.1. Which version are you using?

Download this [1] and move it to `~/.config/karabiner/assets/complex_modifications`. See it if works.

[1] https://github.com/MuhammedZakir/KE-complex_modifications/raw/016fcf44ab6b358ccf1a023e9eca8372ec2395fc/public/json/ultimate_macOS.json.

**Comment by XIYO** [comment]
Sorry. GitHub is still inexperienced.
Currently there were many problems with os, so I proceeded with initialization.
After that, the problem does not occur. Thank you very much for your help.

**Comment by MuhammedZakir** [comment]
> Sorry. GitHub is still inexperienced.

It's okay! :-)

> Currently there were many problems with os, so I proceeded with initialization.
> After that, the problem does not occur.

Glad to hear that! If your problem is solved, then please close this issue!

> Thank you very much for your help.

You're welcome! 😄
