### ISSUE TITLE
command+control+option+shift complex modification not working for hotkey trigger in Keyboard Maestro

### ISSUE THREAD

**Issue by djfayer** [pqrs-org/KE-complex_modifications#774]
command+control+option+shift complex modification not working for hotkey trigger in Keyboard Maestro input field.
Seems to work for existing command+control+option+shift shortcuts but trying to create and assign a new one fails. Using Big Sur 11.0 Beta (20A5395g) and  KM 9.0.6

**Comment by MuhammedZakir** [comment]
Which complex modification did you use? If it's a modification written by you, then please post your complex modification here. Also, I couldn't understand what you want to do. Please explain more about it.

**Comment by djfayer** [comment]
OK. I am trying to use the prebuilt map in Karabiner mapping the CapsLock to command+control+option+shift complex modification (per the Brett Terprsta article) to use with Keyboard Maestro as hotkey trigger (command+control+option+shift+W) to control windows palette in Keyboard Maestro. Still works like a champ with other hotkey triggers prior to Big Sur update. i.e. command+control+option+shift +P controls another palette.
<img width="196" alt="image" src="https://user-images.githubusercontent.com/73127812/99128285-474ad580-25bf-11eb-8d42-f4f8317e941d.png">
<img width="424" alt="image" src="https://user-images.githubusercontent.com/73127812/99128325-592c7880-25bf-11eb-91f0-c339bf7e721b.png">

**Comment by djfayer** [comment]
Thank you. Solved in other forum. It was KM problem. https://forum.keyboardmaestro.com/t/unable-to-type-in-a-hotkey-for-a-macro/19740/8

**Comment by MuhammedZakir** [comment]
You're welcome! :-)

I'm closing this. Feel free to reopen or open a new issue if you had any issue with KE.
