### ISSUE TITLE
fn+button1 (left click) to MMB

### ISSUE THREAD

**Issue by benskk** [pqrs-org/KE-complex_modifications#786]
I'm trying to make a complex modification so that fn+button1(LMB) equals MMB. By default on the Mac, ctrl+button1(LMB) equals RMB. I'm trying to make the same for MMB, only using fn as the modifier key.

In the past I've always mapped fn directly to MMB, but this command performs a MMB without having to click, which in some cases is undesirable. I'm unable to find an example of a complex modification using a mouse click + key_code. Is this possible?

**Comment by MuhammedZakir** [comment]
It's possible. You just have to use `pointing_button` instead of `key_code` for mouse buttons. Everything else is same.

**Comment by benskk** [comment]
So how should that look? Below is what I'm using for a simple fn to MMB … but where should "pointing_button": "button1" be placed so that fn+click = MMB?

{
      "description": "MARVELOUS DESIGNER fn to MMB",
      "manipulators": [
        {
          "type": "basic",
          "from": {
            "key_code": "fn",
            "modifiers": {
              "optional": [
                "any"
              ]
            }
          },
          "to": [
            {
              "pointing_button": "button3"
            }
          ],
          "conditions": [
            {
              "type": "frontmost_application_if",
              "bundle_identifiers": [
              "^com.clo3d.security.clo"
              ]
            }
          ]
        }

      ]
    }

**Comment by MuhammedZakir** [comment]
1. key code `fn` with pointing button `button1`
2. `fn` in `modifiers.mandatory`
3. `modifiers.optional` - you can use `caps_lock` or `any` (up to you).

```json
      "from": {
        "pointing_button": "button1",
        "modifiers": {
          "mandatory": [
            "fn"
          ],
          "optional": [
            "any"
          ]
        }
      },
```

**Comment by benskk** [comment]
Doesn't seem to work for me. Maybe it's the apps I'm using, but anything with button1 doesn't seem to work. I don't think it's possible to get the behaviour I'm looking for.

In my 3D application when I rotate, zoom and pan with LMB, RMB and MMB, I would usually have to click (or make contact with the Wacom) to perform the action, but if I set my fn key directly to MMB, the click (or contact) isn't necessary, I can perform the action with the Wacom stylus hovering above the surface, or moving the mouse without any button pressed. I was just trying to make it so that to perform a camera pan (MMB) I actually have to click whilst pressing fn.

Thanks for you help though.

**Comment by MuhammedZakir** [comment]
You're right. I just gave this a try in Big Sur and it didn't work. There are lot of compatibility issues in both Catalina and Big Sur. This looks like another one of those issues. :-( FWIW, this does work in Mojave.

**Comment by benskk** [comment]
I'm trying it on High Sierra, but I do also have a Big Sur iMac to hand… I guess it's no big deal, I can live with it the way it is. I've just been getting a small problem with the fn to MMB in an application update, but it seems that it's OK when the application registers a click, which got me thinking about why fn to MMB works without requiring any click (or Wacom contact), whereas a normal LMB and RMB (ctrl+LMB on Mac) does require a click.

Thanks for your help, really appreciate it.

**Comment by MuhammedZakir** [comment]
Looks like this bug was fixed in an update. [1] But it happened again! :-(

ping @tekezo: I used latest beta version.

[1] https://github.com/pqrs-org/Karabiner-Elements/issues/2382#issuecomment-731714915
