### ISSUE TITLE
Can't create multi-tap modification for Ctrl+1

### ISSUE THREAD

**Issue by Vorontsovv** [pqrs-org/KE-complex_modifications#808]
Hello, I've made quite a lot of hotkeys with Karabiner and I'm loving it so far. However, there is one type of hotkey I haven't really been able to figure out and I can't find any public .json that does this, or anything in the documentation.

What I'm trying to do is press Ctrl+1 once and have it press K. But then after that I would like to press Ctrl+1 again, but have it press G. I suspect this also could be possible by treating Ctrl as a key that you hold in and 1 as they key you have to press multiple times.

(From) key_code 1, mandatory modifier: left_control

(To) K, after another press, to G

Hope that explains it

**Comment by Vorontsovv** [comment]
While this isn't a solution, this is the closest I've gotten, it works somewhat alright. When you tap Ctrl+1 it will run Ctrl+4, When you hold in Ctrl+1 for 100ms which I've set in my karabiner parameters, it will run Ctrl+6

>     {
>       "manipulators": [
>         {
>           "type": "basic",
>           "from": {
>             "modifiers": {
>               "mandatory": [
>                 "left_control"
>               ]
>             },
>             "key_code": "1"
>           },
>           "to": [
>             {
>               "key_code": "4",
>               "modifiers": [
>                 "left_control"
>               ]
>             }
>           ],
>           "to_if_held_down": [
>             {
>               "key_code": "6",
>               "modifiers": [
>                 "left_control"
>               ]
>             }
>           ]
>         }
>       ],
>       "description": "Toggle Shaded w/ Wireframe"
>     }

**Comment by MuhammedZakir** [comment]
Have you tried `variable_if` condition?

[1] https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/conditions/variable/
