### ISSUE TITLE
Exclude Rule for specific application

### ISSUE THREAD

**Issue by suntong** [pqrs-org/KE-complex_modifications#812]
Following up on #56, 

How to find out what to put within the `bundle_identifiers`?

The app that I want to exclude the rule from is xterm, installed from MacPorts. 
How do I know what its `bundle_identifiers` is? Thx

**Comment by MuhammedZakir** [comment]
https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/conditions/frontmost-application/#investigate-the-bundle-identifier-and-file-path
