### ISSUE TITLE
Windows shortcuts on macOS, to exclude X11 Macports apps

### ISSUE THREAD

**Issue by suntong** [pqrs-org/KE-complex_modifications#816]
Following up on #814 

> `^-C` means "Control - Break" way before it means "copy". 

I cannot miss the ability to do "control - break". But now that the rule needs to be as general as possible and cannot replace all `control` with `left_control` for all rules, I'd propose to exclude all X11 Macports apps from the rules, just like apple Terminal is excluded from the rules too.

I've successfully change it locally. OK I send in the PR?

**Comment by MuhammedZakir** [comment]
```
[...] I'd propose to exclude all X11 Macports apps from the rules [...]
```

Is there an easy way to do that?

> I've successfully change it locally. OK I send in the PR?

Yes. Open a PR and if there is no issue, I will merge it.
