### ISSUE TITLE
Goku / EDN versions of these complex modifications?

### ISSUE THREAD

**Issue by pragmat1c1** [pqrs-org/KE-complex_modifications#818]
I've been using using four complex modifications happily [1].

Recently I learned about Goku and EDN files, and I'd love to migrate my complex modifications (json files) to EDN files.

Are there EDN versions of these files that I am not aware of? 

[1]: List of the "complex modifications" I use

- Change fn-key to command+control+option+shift.
- Post left_ctrl when return_or_enter is hold.
- Post escape if caps is pressed alone, left_ctrl otherwise
- Emacs key bindings [control+keys] (rev 10)

**Comment by MuhammedZakir** [comment]
Try googling. If there is no results, then you probably have to do it yourself. Anyway, you are better of asking this in Goku repo.
