### ISSUE TITLE
Middle click with Apple mouse/pad

### ISSUE THREAD

**Issue by suntong** [pqrs-org/KE-complex_modifications#828]
I miss the ability to do middle click in Windows. On seeing many app are configuring Option+Left Click as middle button themselves, I'm trying to do with Karabiner:

                    {
                        "description": "Option+Left Click => middle button",
                        "manipulators": [
                            {
                                "from": {
                                    "modifiers": {
                                        "mandatory": [
                                            "left_option"
                                        ],
                                        "optional": [
                                            "any"
                                        ]
                                    },
                                    "pointing_button": "button1"
                                },
                                "to": [
                                    {
                                        "pointing_button": "button3"
                                    }
                                ],
                                "type": "basic"
                            }
                        ]
                    }

However, I don't know why it is not working. 

Anyone can help pls?

@MuhammedZakir, if I get it right in the end, OK that send in the PR to your Windows shortcuts on macOS?

thx

**Comment by MuhammedZakir** [comment]
IIRC, mouse button with modifier combination does not work in 10.15+. I am not sure if this is fixed in latest version or not, but considering your code is correct, it's most plausibly not fixed. I will give you an answer after I test it. 

> @MuhammedZakir, if I get it right in the end, OK that send in the PR to your Windows shortcuts on macOS?

 That's not mine. :-)
