### ISSUE TITLE
no lesser than / greater than

### ISSUE THREAD

**Issue by BenoitOClock** [pqrs-org/KE-complex_modifications#868]
Hey,

I'm using Karabiner to invert cmd and ctrl key when workin with nomachine.
I'm using a french magic keyboard with numeric keypad.

It works fine yet it has an annoying side effect. When i type "<" I get a "@" and when i type a ">" I get a '#".

how can i solve that problem ?

**Comment by MuhammedZakir** [comment]
That's a bug and it probably won't be fixed soon. The only option atm is to map those keys.
