### ISSUE TITLE
long press a charecter to replace with another one

### ISSUE THREAD

**Issue by ashickur-rahman** [pqrs-org/KE-complex_modifications#869]
"f" key of my keyboard is not working. I am trying to set a rules like this, if I long press "d" , "f" will the trigger. I failed to understand [Karabiner Complex Modification](https://genesy.github.io/karabiner-complex-rules-generator/) . Help from anybody will be appreciated.

**Comment by MuhammedZakir** [comment]
Have you tried `to_if_held_down` [1]?

[1] https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/to-if-held-down/
