### ISSUE TITLE
External keyboard: Less-than / greater-than exchanged by circumflex / circle when KE is running

### ISSUE THREAD

**Issue by p10n** [pqrs-org/KE-complex_modifications#870]
Actually, maybe this is 2 issues:
I have a German keyboard on my MacBook.
The first top-left key is ^/° (circumflex/circle accent), and next to the left shift key, there is </> (less-than/greater-than).
All fine.

Now I connect an external PC keyboard, which has the same layout. The assistant of OS X asks me to press the first key next to the left shift-key (which is the said </> key) - it asks this because there are layouts which have the </> and ^/° keys at the opposite locations.
**Bug 1:** When I try to do as I was told, it claims that I would have pressed a key on the internal keyboard (which was not true) - obviously a side-effect ot KE being active. So I quit KE, disconnect and re-connect the keyboard and press the key again - fine.
The external keyboard works as expected.

Now I start KE.
**Bug 2:** Now, the </> and the ^/° keys are exchanged, ONLY on the external keyboard. The internal keyboard still works as expected. 

I suspect that KE seems to ignore the ordering of these two keys that was gained by the OSX setup assistant - could this be the case?
Is this a known bug, and is there a chance it gets fixed?

Probably a workaround would be to explicitly map these 2 pairs of characters to the respective other pair, only for the external keyboard. (I have not tried yet, probably a little bit tricky as the circumflex is a semi-dead key waiting for the character to follow, not sure how I would need to account for this in the json.)

**Comment by MuhammedZakir** [comment]
> Is this a known bug, and is there a chance it gets fixed?

It's a longstanding bug. Search "swap" in issues in Karabiner-Elements repo.

> Probably a workaround would be to explicitly map these 2 pairs of characters to the respective other pair, only for the external keyboard. (I have not tried yet, probably a little bit tricky as the circumflex is a semi-dead key waiting for the character to follow, not sure how I would need to account for this in the json.)

https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/conditions/device/
