### ISSUE TITLE
new imac m1 touch ID issue.

### ISSUE THREAD

**Issue by locusok** [pqrs-org/KE-complex_modifications#884]
The new iMac has Touch ID.
If I use karabiner on the Touch ID keyboard, I cannot switch users using touch ID.

**Comment by tekezo** [comment]
Hmm, I don't have the device at the moment, so I can't check .......

Is Touch ID detected as separated device from keyboard?
https://karabiner-elements.pqrs.org/docs/manual/configuration/configure-devices/

If so, does turning the checkbox off solves this issue?

**Comment by locusok** [comment]
<img width="1112" alt="스크린샷 2021-06-23 오후 10 09 43" src="https://user-images.githubusercontent.com/85011117/123102512-18a7ae00-d470-11eb-9c97-13473b7a051e.png">

Yes. Touch ID detected the Magic keyboard with Touch ID (Apple)
If this device is checked, the Touch ID key cannot be input.

**Comment by tekezo** [comment]
Thank you!
Hmm, that makes it a bit difficult to deal with at the moment.
I'll check after the keyboard is sold separately.
