### ISSUE TITLE
Is there a good reason PC style Home/end is conspiquously missing?

### ISSUE THREAD

**Issue by ktaragorn** [pqrs-org/KE-complex_modifications#90]

**Comment by apm1467** [comment]
No, there's not good reason. So, indeed,[ they are not missing](https://github.com/tekezo/Karabiner-Elements/blob/master/src/apps/PreferencesWindow/PreferencesWindow/Resources/simple_modifications.json#L127-L132).

**Comment by ktaragorn** [comment]
I mean the mapping of home to command left, while I believe you pointed
more to the list of keys in the simple rules configuration window, right?

**Comment by apm1467** [comment]
I see what you mean. If you need these rules, please feel free to implement them and raise a pull request. 

What I showed was the list of all key names that can be used in simple/complex modifications.

**Comment by ktaragorn** [comment]
Yeah.. I need and I am trying to implement. This and mapping eject key to F12(cant any more :( )  is all I use karabiner for. I am trying to implement

**Comment by ktaragorn** [comment]
PRed!
