### ISSUE TITLE
Neo2 - Mod4 Lock single key activation

### ISSUE THREAD

**Issue by ody55eus** [pqrs-org/KE-complex_modifications#902]
I am using Karabiner with Neo2 Layout on the new M1 MacBook (Mac OS 11.4 Big Sur).
I've encountered a problem when activating the rules of "Neo2 mod 3 and 4 keys (Apple keyboard). Toggle mod4 by pressing both mod4 keys simultaneously."

## Problem

When the right-command or tilde key (mod4 modifier key) is pressed **once alone** (without entering any key from mod4), the mod4 **lock activates**. This should only happen when pressing both modifiers simultaneously.

## Solution

I've created the following patch which solves this problem for me:
https://gist.github.com/ody55eus/84e91391bf02b8f714175bc4f0c6918f

**Comment by max-toepfer** [comment]
@ody55eus , I face a similar issue, when pressing the left Mod4 button, having the rule "Neo2 mod 3 and 4 keys (Windows keyboard)" activated.
I'd love to use your patch, but I seem to miss a few breadcrumbs on the way to salvation. Could you elaborate on how to apply the patch? I already got the "KE-complex_modifications" repo checked out, but I can't seem to find the file, that you patch fixes.
Thank you in advance!

**Comment by ody55eus** [comment]
Download the json file from https://ke-complex-modifications.pqrs.org/json/neo2.json
and apply the patch from above:

```
curl https://ke-complex-modifications.pqrs.org/json/neo2.json -o neo2.json
curl https://gist.githubusercontent.com/ody55eus/84e91391bf02b8f714175bc4f0c6918f/raw/98a8b18b974076d011a8fbe3b32c41bc92844fc3/neo2-mod4.patch -o neo2-mod4.patch
patch neo2.json neo2-mod4.patch
```
