### ISSUE TITLE
No way to make a Fn+Control complex modification

### ISSUE THREAD

**Issue by basnyder** [pqrs-org/KE-complex_modifications#903]
On mac, no way to map Fn+Control+arrow keys to an action, or at least that I've seen. Any suggestions?

**Comment by MuhammedZakir** [comment]
When you press arrow keys with `Fn`+Control`, does mac detects it? You can use an on-screen keyboard, or EventViewer to check it.

**Comment by basnyder** [comment]
It logs in the misc column "flags fn,right_control"

**Comment by MuhammedZakir** [comment]
Have you enabled your device in `Karabiner-Elements Preferences > Devices`? Also, what do you mean by "action"? Can you explain what you want to do?
