### ISSUE TITLE
double tap right shift 

### ISSUE THREAD

**Issue by drewauff** [pqrs-org/KE-complex_modifications#922]
How can I run a command (or invoke a shortcut/ zle command) in iTerm by double tapping right shift?

ie. 2x R-Shift = fzf-cd-widget

I have found one(Terminal Helper) that should work but modding it has no effect at all.

I created an zle widget called fzf-cd-widget which currently bound to ^M^M (double tap enter key), I want to change this to double tap right shift key. How?
edit: spent the past few hours trying to get this working but to no avail. I have read the the documentation but that was of little help.. I did find this snippet
```
{
    "to": [
        {
            "shell_command": "/bin/sh ~/opt/shell_commands/hello.sh"
        }
    ]
}

```
Does not seem to matter where i put it, it has no effect.

This is the code I am attempting to mod (I dont need the left shift mod)

I hope someone can help, I am really lost.

```
{
  "title": "Shell helpers",
  "rules": [
    {
      "description": "Double tap left-shift to return ~/",
      "manipulators": [
        {
          "type": "basic",
          "from": {
            "key_code": "left_shift",
            "modifiers": {
              "optional": [
                "any"
              ]
            }
          },
          "to": [
            {
              "key_code": "grave_accent_and_tilde",
              "modifiers": [
                "shift"
              ]
            },
            {
              "key_code": "slash"
            }
          ],
          "conditions": [
            {
              "type": "variable_if",
              "name": "left_shift pressed",
              "value": 1
            }
          ]
        },
        {
          "type": "basic",
          "from": {
            "key_code": "left_shift",
            "modifiers": {
              "optional": [
                "any"
              ]
            }
          },
          "to": [
            {
              "set_variable": {
                "name": "left_shift pressed",
                "value": 1
              }
            },
            {
              "key_code": "left_shift"
            }
          ],
          "to_delayed_action": {
            "to_if_invoked": [
              {
                "set_variable": {
                  "name": "left_shift pressed",
                  "value": 0
                }
              }
            ],
            "to_if_canceled": [
              {
                "set_variable": {
                  "name": "left_shift pressed",
                  "value": 0
                }
              }
            ]
          }
        }
      ]
    },
    {
      "description": "Double tap right-shift to return ~/.",
      "manipulators": [
        {
          "type": "basic",
          "from": {
            "key_code": "right_shift",
            "modifiers": {
              "optional": [
                "any"
              ]
            }
          },
          "to": [
            {
              "key_code": "grave_accent_and_tilde",
              "modifiers": [
                "shift"
              ]
            },
            {
              "to": [
                {
                  "shell_command": "fzf-cd-widget"
                }
              ]
            }
          ],
          "conditions": [
            {
              "type": "variable_if",
              "name": "right_shift pressed",
              "value": 1
            }
          ]
        },
        {
          "type": "basic",
          "from": {
            "key_code": "right_shift",
            "modifiers": {
              "optional": [
                "any"
              ]
            }
          },
          "to": [
            {
              "set_variable": {
                "name": "right_shift pressed",
                "value": 1
              }
            },
            {
              "key_code": "right_shift"
            }
          ],
          "to_delayed_action": {
            "to_if_invoked": [
              {
                "set_variable": {
                  "name": "right_shift pressed",
                  "value": 0
                }
              }
            ],
            "to_if_canceled": [
              {
                "set_variable": {
                  "name": "right_shift pressed",
                  "value": 0
                }
              }
            ]
          }
        }
      ]
    }
  ]
}

```

**Comment by MuhammedZakir** [comment]
`shell_command` will be executed by Karabiner in a different shell/process, and not in the currently opened/focused shell.

---

There are three ways to do what you want:

1. Send an array of `to` events corresponding to the shell command (replace `...` with actual key codes).
```
"to": [
  {
    "key_code": "f"
  },
  {
    "key_code": "z"
  },
  {
    "key_code": "f"
  },
  ...
]
```

2. Use AppleScript.
```
"to": [
  {
    "shell_command": "osascript -e 'tell application \"System Events\" to keystroke \"fzf-cd-widget\"' "
  }
]
```

3. Use clibpoard.
```
"to": [
  {
    "shell_command": "printf 'fzf-cd-widget' | pbcopy"
  }
],
"to_delayed_action": {
  "to_if_invoked": [
    {
      "key_code": "v",
      "modifiers": "command"
    }
  ]
},
"parameters": {
  "basic.to_delayed_action_delay_milliseconds": 80
}
```

Note: increase the delay if the current delay is not enough.

**Comment by drewauff** [comment]
WOW! Thank you for the awesome response :)

After seeing your suggestions I think the first is not a great option.

Can  I execute in the current shell/process? possibly an alternative to "shell_command"?

**Comment by drewauff** [comment]
No matter what I do ( I went with the 2nd option) or where I put your suggested code all I get is `~/.`

Maybe, it would be best to start from scratch?

**Comment by MuhammedZakir** [comment]
> WOW! Thank you for the awesome response :)

You're welcome! :-)

> After seeing your suggestions I think the first is not a great option.

You're not alone on that. :-D

> Can I execute in the current shell/process? possibly an alternative to "shell_command"?

What you're asking is not possible. AFAIK, there no reliable way to do that with/without Karabiner either. The best you can do is to insert text at the current cursor location, and then press enter/return manually/automatically.

---

Before importing below config, execute below command in a terminal and see if you get `fzf-cd-widget`. You will have to give access to Accessibility (IIRC) to iTerm2 (if you haven't done it already). This will be asked if you are running it for this first time. Otherwise, you can enabled this in `Accessibility` in `System Preferences > Security and Privacy`

```
osascript -e 'tell application "System Events" to keystroke "fzf-cd-widget"'
```

This is "handwritten", so there maybe typos and some other errors. Check `Karabiner-Elements preferences > Log` for errors when importing.

```
{
  "title": "2x right shift => fzf-cd-widget",
  "rules": [
    {
      "description": "2x right shift => fzf-cd-widget",
      "manipulators": [
        {
          "type": "basic",
          "from": {
            "key_code": "right_shift",
            "modifiers": {
              "optional": ["any"]
            }
          },
          "to": [
            {
              "shell_command": "osascript -e 'tell application \"System Events\" to keystroke \"fzf-cd-widget\"' "
            }
          ],
          "conditions": [
            {
              "type": "variable_if",
              "name": "right_shift pressed",
              "value": 1
            }
          ]
        },
        {
          "type": "basic",
          "from": {
            "key_code": "right_shift",
            "modifiers": {
              "optional": ["any"]
            }
          },
          "to": [
            {
              "set_variable": {
                "name": "right_shift pressed",
                "value": 1
              }
            },
            {
              "key_code": "right_shift"
            }
          ],
          "to_delayed_action": {
            "to_if_invoked": [
              {
                "set_variable": {
                  "name": "right_shift pressed",
                  "value": 0
                }
              }
            ],
            "to_if_canceled": [
              {
                "set_variable": {
                  "name": "right_shift pressed",
                  "value": 0
                }
              }
            ]
          }
        }
      ]
    }
  ]
}
```

Note: Using above config, you will have to press enter/return after the text is entered. You can make this automatic by emitting an enter/return when `shift` is released using `to_after_key_up`, or after a short delay using `to_delayed_action`.

[1] https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/to-delayed-action/
[2] https://karabiner-elements.pqrs.org/docs/json/complex-modifications-manipulator-definition/to-after-key-up/

**Comment by MuhammedZakir** [comment]
To import above config, save it in `~/.config/karabiner/assets/complex_modifications/somefile.json`, and then import it using `Add Rule` in `Karabiner-Elements Preferences > Complex Modifications`.

**Comment by drewauff** [comment]
It only allows import from web page..

**Comment by drewauff** [comment]
sadly didnt work, checked log and this error was highlighted
`[2021-08-22 19:58:39.987] [error] [grabber] karabiner.json error: `to_after_key_up` error: unknown key `to_if_canceled` in `{"to_if_canceled":[{"set_variable":{"name":"right_shift pressed","value":0}}],"to_if_invoked":[{"set_variable":{"name":"right_shift pressed","value":0}}]}`
`

**Comment by drewauff** [comment]
works with `to_delayed_action`

but doesnt work with `to_after_key_up`

Am I supposed replace the former with the later?

**Comment by MuhammedZakir** [comment]
If I'm understanding the error correctly, you used `to_if_invoked` and `to_if_canceled` in `to_after_key_up`. It's wrong. They can only be used inside `to_delayed_action`.

> need to have it execute with double, without hitting enter.

This will enter `fzf-cd-widget` when pressing right shift twice, and will send an enter when the shift is released.

```
{
  "title": "2x right shift => fzf-cd-widget",
  "rules": [
    {
      "description": "2x right shift => fzf-cd-widget",
      "manipulators": [
        {
          "type": "basic",
          "from": {
            "key_code": "right_shift",
            "modifiers": {
              "optional": ["any"]
            }
          },
          "to": [
            {
              "shell_command": "osascript -e 'tell application \"System Events\" to keystroke \"fzf-cd-widget\"' "
            }
          ],
          "to_after_key_up": [
            {
              "key_code": "return_or_enter"
            }
          ],
          "conditions": [
            {
              "type": "variable_if",
              "name": "right_shift pressed",
              "value": 1
            }
          ]
        },
        {
          "type": "basic",
          "from": {
            "key_code": "right_shift",
            "modifiers": {
              "optional": ["any"]
            }
          },
          "to": [
            {
              "set_variable": {
                "name": "right_shift pressed",
                "value": 1
              }
            },
            {
              "key_code": "right_shift"
            }
          ],
          "to_delayed_action": {
            "to_if_invoked": [
              {
                "set_variable": {
                  "name": "right_shift pressed",
                  "value": 0
                }
              }
            ],
            "to_if_canceled": [
              {
                "set_variable": {
                  "name": "right_shift pressed",
                  "value": 0
                }
              }
            ]
          }
        }
      ]
    }
  ]
}
```

**Comment by drewauff** [comment]
Unfortunately this doesn't work either, just displays the text "fzf-cd-widget"

**Comment by MuhammedZakir** [comment]
This should work.

Note: Again, check for any syntax errors in the log.

```
{
  "title": "2x right shift => fzf-cd-widget",
  "rules": [
    {
      "description": "2x right shift => fzf-cd-widget",
      "manipulators": [
        {
          "type": "basic",
          "conditions": [
            {
              "type": "variable_if",
              "name": "right_shift pressed",
              "value": 1
            }
          ],
          "from": {
            "key_code": "right_shift",
            "modifiers": {
              "optional": ["any"]
            }
          },
          "to": [
            {
              "shell_command": "osascript -e 'tell application \"System Events\" to keystroke \"fzf-cd-widget\"' "
            }
          ],
          "to_delayed_action": {
            "to_if_invoked": [
              {
                "key_code": "return_or_enter"
              }
            ]
          },
          "parameters": {
            "basic.to_delayed_action_delay_milliseconds": 80
          }
        },
        {
          "type": "basic",
          "from": {
            "key_code": "right_shift",
            "modifiers": {
              "optional": ["any"]
            }
          },
          "to": [
            {
              "set_variable": {
                "name": "right_shift pressed",
                "value": 1
              }
            },
            {
              "key_code": "right_shift"
            }
          ],
          "to_delayed_action": {
            "to_if_invoked": [
              {
                "set_variable": {
                  "name": "right_shift pressed",
                  "value": 0
                }
              }
            ],
            "to_if_canceled": [
              {
                "set_variable": {
                  "name": "right_shift pressed",
                  "value": 0
                }
              }
            ]
          }
        }
      ]
    }
  ]
}
```

**Comment by drewauff** [comment]
It works but I have to double tap twice for it to work

**Comment by drewauff** [comment]
Ok so it works like this..

double tap => inputs command => double executes the command

**Comment by MuhammedZakir** [comment]
If it still doesn't work, try the below config. Increase `hold_down_milliseconds` if it's not enough.


P.S. When testing, use EventViewer. Check if you get `fzf-cd-widget` and then an enter. If it doesn't work as expected, please post EventViewer output. I am also curious about what output you get when use the above config.

```
{
  "title": "2x right shift => fzf-cd-widget",
  "rules": [
    {
      "description": "2x right shift => fzf-cd-widget",
      "manipulators": [
        {
          "type": "basic",
          "conditions": [
            {
              "type": "variable_if",
              "name": "right_shift pressed",
              "value": 1
            }
          ],
          "from": {
            "key_code": "right_shift",
            "modifiers": {
              "optional": ["any"]
            }
          },
          "to": [
            {
              "shell_command": "osascript -e 'tell application \"System Events\" to keystroke \"fzf-cd-widget\"' "
            },
            {
              "key_code": "vk_none",
              "hold_down_milliseconds": 100
            },
            {
              "key_code": "return_or_enter"
            }
          ]
        },
        {
          "type": "basic",
          "from": {
            "key_code": "right_shift",
            "modifiers": {
              "optional": ["any"]
            }
          },
          "to": [
            {
              "set_variable": {
                "name": "right_shift pressed",
                "value": 1
              }
            },
            {
              "key_code": "right_shift"
            }
          ],
          "to_delayed_action": {
            "to_if_invoked": [
              {
                "set_variable": {
                  "name": "right_shift pressed",
                  "value": 0
                }
              }
            ],
            "to_if_canceled": [
              {
                "set_variable": {
                  "name": "right_shift pressed",
                  "value": 0
                }
              }
            ]
          }
        }
      ]
    }
  ]
}
```

**Comment by drewauff** [comment]
I want use double tap right-shift  to bring up dir listing via fzf, I have bound double tap enter to list editable files and open them. I have tried man different binds but double tap of the larger keys (enter & shift) make it much easier and therefore faster to utilise. I have bound space double but that turned out to be not such a good idea.

You see when you are on the "home" row, it is extremely intuitive to just hit the enter or right-shift key and this is enhanced by the larger physical size of the keys.

Having said that, I will stick to the pbcopy method and will see if I can find a way to hide the command from the prompt.

side note, the command `fzcd` is actually not being written to my history.

I know, in other scripts and such that I have written, that I can hide the input, output, or error output, which basically runs the command in the background (nothing visible — maybe one day ill tackle progress bars).

I just can't get it to work.

for example I created this script (yes its part of zle widget)

`fls f -alh | awk '{print $1, $5, $9}' | column -t | fzf --tac | awk '{print $3}' | xargs rm 2>/dev/null`

In this example if I dont "route" it to /dev/null then I get an output error message (non-critical, a warning if you will).

So, you see, it can be done but, I cant get it to work in Karabiner.

**Comment by drewauff** [comment]
Ok, I had a thought, I added `cut -d 'f' -f1-` that suppress the fzcd part but the part that I need to suppress/hide is the cmd+v output and I think a redirect to /dev/null will do it as it reads the clipboard without showing the output cmd-v.

**Comment by drewauff** [comment]
If I map the command to eg. F20 — in our current script, is it possible to map F20 to a right-shift double tap?

ie. double tap right-shift to initiate F20?

If so this would solve everything..i think

**Comment by drewauff** [comment]
Ok it works, I temporarily bound to F6.. but I need it for another things.. can I bind to a function key I dont have? 
Im on MacOS and only go up to F13 (remapped the power button).

**Comment by drewauff** [comment]
This is the current script:
Ho to make it work for iTerm only?

`{
  "title": "2x right shift => fzf-cd-widget",
  "rules": [
    {
      "description": "2x right shift => fzf-cd-widget",
      "manipulators": [
        {
          "type": "basic",
          "conditions": [
            {
              "type": "variable_if",
              "name": "right_shift pressed",
              "value": 1
            }
          ],
          "from": {
            "key_code": "right_shift",
            "modifiers": {
              "optional": ["any"]
            }
          },
          
          "to_delayed_action": {
            "to_if_invoked": [
{
                 "key_code": "f20"
  },
  {
    "key_code": "return_or_enter"
  }
]
          },
          "parameters": {
            "basic.to_delayed_action_delay_milliseconds": 0
          }
        },
        {
          "type": "basic",
          "from": {
            "key_code": "right_shift",
            "modifiers": {
              "optional": ["any"]
            }
          },
          "to": [
            {
              "set_variable": {
                "name": "right_shift pressed",
                "value": 1
              }
            },
            {
              "key_code": "right_shift"
            }
          ],
          "to_delayed_action": {
            "to_if_invoked": [
              {
                "set_variable": {
                  "name": "right_shift pressed",
                  "value": 0
                }
              }
            ],
            "to_if_canceled": [
              {
                "set_variable": {
                  "name": "right_shift pressed",
                  "value": 0
                }
              }
            ]
          }
        }
      ]
    }
  ]
}
`

**Comment by MuhammedZakir** [comment]
> If I map the command to eg. F20 — in our current script, is it possible to map F20 to a right-shift double tap?
> 
> ie. double tap right-shift to initiate F20?
> 
> If so this would solve everything..i think

Yes. Map double tap `right_shift` to `F20` in Karabiner, and then map/bind `F20` to your command in shell.

> edit: so binding function keys using bindkey is `^[[21~` — I think this would bind F20..correct?

I haven't checked it, and the sequence is sometimes different on different computers.

**Comment by drewauff** [comment]
It didnt matter what I tried to bind to from f14 above, it binds ==> runs the widget but does not however run the command inside the widget. If I setup a direct bind ie. bindkey 'thefucntionkeyofchoice' "thecommand" it does not work. 

 The app im using is called PowerKey and its very very unstable..I am now looking for an alternative..

**Comment by MuhammedZakir** [comment]
> [...] If I setup a direct bind ie. bindkey 'thefucntionkeyofchoice' "thecommand" it does not work.

Why? If you have setup everything correctly and is pressing the correct key, then everything should work. Try testing with this:

1. `test () { echo a }`
2.  `zle -N test`
3. ` bindkey '^[OS' test` -- `^[OS` is the sequence I get for `F4` (replace it if yours is different).
4. Now, pressing `F4` should get an `a` and a newline.

If this doesn't work, then there is some problem with you ZSH setup.

**Comment by drewauff** [comment]
The widget in question :

```
fzf-cd-widget() {
     zle reset-prompt
      cd $(fd --type directory --min-depth 1 --prune  | fzf --tac) &&
}
zle -N fzf-cd-widget
bindkey '\e[17~' "fzf-cd-widget"
```
(currently bound to F6) and works flawlessly

If I bind to anything 14 or above it does not complete.

Binding to F14 or above Example:
The widget brings up (via fzf) a list of all directories in the current directory, then you can scroll and pick the dir. or start typing the dir. you want and hit enter to traverse. THIS IS WHERE THE PROBLEM OCCURS. Hitting enter just returns you to the prompt without the dir. change. I have no Idea why.

**Comment by MuhammedZakir** [comment]
That's strange. I mapped double tap `right_shift` to `f20`, and bound `f20` to your command in ZSH. After that, I am able to change directory with by double tapping `right_shift`.

Few things I would do:
1. Check if your complex modification is correct. That is, you are only getting a `right_shift` and `F14`.
2. Make sure the sequence you used in `bindkey` command is correct.
3. Try other functions keys (14-20).

Your problem has to do with ZSH, and I am not familiar with ZSH ZLE enough to guess the problem. It's better to ask this in a ZSH forum/chatroom.
