### ISSUE TITLE
Swap Cmd and Cntrl in Parsec App

### ISSUE THREAD

**Issue by robtravis** [pqrs-org/KE-complex_modifications#944]
I use Parsec to control my PC from my Mac and would love to be able to swap the Cmd and Cntrl keys and map Alt to Opt for only that app. I've tried to modify some existing complex_modifications and use the generator, but I can't get it to work, so I'm probably doing something wrong. If anyone could build and publish an application specific modification for Parsec with those mods that would be awesome. I believe the Bundle Identifier is tv.parsec.www.

**Comment by robtravis** [comment]
Here is my code. I modified one that does similar function for Microsoft RD.

  "title": "Parsec",
  "rules": [
    {
      "description": "Swap command and control",
      "manipulators": [
        {
          "type": "basic",
          "from": {
            "key_code": "left_control",
            "modifiers": {
              "optional": [
                "any"
              ]
            }
          },
          "to": [
            {
              "key_code": "left_command"
            }
          ],
          "conditions": [
            {
              "type": "frontmost_application_if",
              "bundle_identifiers": [
                "tv\\.parsec\\.www"
              ]
            }
          ]
        },
        {
          "type": "basic",
          "from": {
            "key_code": "left_command",
            "modifiers": {
              "optional": [
                "any"
              ]
            }
          },
          "to": [
            {
              "key_code": "left_control"
            }
          ],
          "conditions": [
            {
              "type": "frontmost_application_if",
              "bundle_identifiers": [
                "tv\\.parsec\\.www"
              ]
            }
          ]
        },
        {
          "type": "basic",
          "from": {
            "key_code": "right_control",
            "modifiers": {
              "optional": [
                "any"
              ]
            }
          },
          "to": [
            {
              "key_code": "right_command"
            }
          ],
          "conditions": [
            {
              "type": "frontmost_application_if",
              "bundle_identifiers": [
                "tv\\.parsec\\.www"
              ]
            }
          ]
        },
        {
          "type": "basic",
          "from": {
            "key_code": "right_command",
            "modifiers": {
              "optional": [
                "any"
              ]
            }
          },
          "to": [
            {
              "key_code": "right_control"
            }
          ],
          "conditions": [
            {
              "type": "frontmost_application_if",
              "bundle_identifiers": [
                "tv\\.parsec\\.www"
              ]
            }
          ]
        }

      ]
    }
  ]
}

**Comment by MuhammedZakir** [comment]
There is one `{` at the start of the config.

After you imported this, did `Karabiner-Elements Preferences > Log` show any error? What does EventViewer show when you use Parsec app and when you don't use it?

**Comment by MuhammedZakir** [comment]
I think I found the problem. You are using a slanted quotes instead of straight quotes (`"`). You can see that some quoted parts of your config are being highlighted in Github [1].

FWIW: if you are using TextEdit to edit the config, IIAR, using a monospaced font fixes the problem.

[1] https://github.com/robtravis/Parsec-Karabiner/blob/main/Karabiner-Parsec.json

**Comment by skoshy** [comment]
I wanted to do the same (swap control and command keys in Parsec), so I made this config. You can install it directly from the [JSON editor here](https://genesy.github.io/karabiner-complex-rules-generator/#eyJ0aXRsZSI6IlN3YXAgQ01EIGFuZCBDb250cm9sIGtleXMgaW4gUGFyc2VjIiwicnVsZXMiOlt7ImRlc2NyaXB0aW9uIjoiU3dhcCBDTUQgYW5kIENvbnRyb2wga2V5cyBpbiBQYXJzZWMiLCJtYW5pcHVsYXRvcnMiOlt7InR5cGUiOiJiYXNpYyIsImNvbmRpdGlvbnMiOlt7InR5cGUiOiJmcm9udG1vc3RfYXBwbGljYXRpb25faWYiLCJidW5kbGVfaWRlbnRpZmllcnMiOlsiXnR2XFwucGFyc2VjXFwud3d3JCJdfV0sImZyb20iOnsia2V5X2NvZGUiOiJsZWZ0X2NvbW1hbmQiLCJtb2RpZmllcnMiOnsib3B0aW9uYWwiOlsiYW55Il19fSwidG8iOlt7ImtleV9jb2RlIjoibGVmdF9jb250cm9sIn1dfSx7InR5cGUiOiJiYXNpYyIsImNvbmRpdGlvbnMiOlt7InR5cGUiOiJmcm9udG1vc3RfYXBwbGljYXRpb25faWYiLCJidW5kbGVfaWRlbnRpZmllcnMiOlsiXnR2XFwucGFyc2VjXFwud3d3JCJdfV0sImZyb20iOnsia2V5X2NvZGUiOiJyaWdodF9jb21tYW5kIiwibW9kaWZpZXJzIjp7Im9wdGlvbmFsIjpbImFueSJdfX0sInRvIjpbeyJrZXlfY29kZSI6InJpZ2h0X2NvbnRyb2wifV19LHsidHlwZSI6ImJhc2ljIiwiY29uZGl0aW9ucyI6W3sidHlwZSI6ImZyb250bW9zdF9hcHBsaWNhdGlvbl9pZiIsImJ1bmRsZV9pZGVudGlmaWVycyI6WyJedHZcXC5wYXJzZWNcXC53d3ckIiwiIiwiIiwiIiwiIiwiIl19XSwiZnJvbSI6eyJrZXlfY29kZSI6ImxlZnRfY29udHJvbCIsIm1vZGlmaWVycyI6eyJvcHRpb25hbCI6WyJhbnkiXX19LCJ0byI6W3sia2V5X2NvZGUiOiJsZWZ0X2NvbW1hbmQifV19LHsidHlwZSI6ImJhc2ljIiwiY29uZGl0aW9ucyI6W3sidHlwZSI6ImZyb250bW9zdF9hcHBsaWNhdGlvbl9pZiIsImJ1bmRsZV9pZGVudGlmaWVycyI6WyJedHZcXC5wYXJzZWNcXC53d3ckIiwiIiwiIiwiIiwiIiwiIl19XSwiZnJvbSI6eyJrZXlfY29kZSI6InJpZ2h0X2NvbnRyb2wiLCJtb2RpZmllcnMiOnsib3B0aW9uYWwiOlsiYW55Il19fSwidG8iOlt7ImtleV9jb2RlIjoicmlnaHRfY29tbWFuZCJ9XX1dfV19).

Raw script:

```json
{
  "title": "Swap CMD and Control keys in Parsec",
  "rules": [
    {
      "description": "Swap CMD and Control keys in Parsec",
      "manipulators": [
        {
          "type": "basic",
          "conditions": [
            {
              "type": "frontmost_application_if",
              "bundle_identifiers": [
                "^tv\\.parsec\\.www$"
              ]
            }
          ],
          "from": {
            "key_code": "left_command",
            "modifiers": {
              "optional": [
                "any"
              ]
            }
          },
          "to": [
            {
              "key_code": "left_control"
            }
          ]
        },
        {
          "type": "basic",
          "conditions": [
            {
              "type": "frontmost_application_if",
              "bundle_identifiers": [
                "^tv\\.parsec\\.www$"
              ]
            }
          ],
          "from": {
            "key_code": "right_command",
            "modifiers": {
              "optional": [
                "any"
              ]
            }
          },
          "to": [
            {
              "key_code": "right_control"
            }
          ]
        },
        {
          "type": "basic",
          "conditions": [
            {
              "type": "frontmost_application_if",
              "bundle_identifiers": [
                "^tv\\.parsec\\.www$",
                "",
                "",
                "",
                "",
                ""
              ]
            }
          ],
          "from": {
            "key_code": "left_control",
            "modifiers": {
              "optional": [
                "any"
              ]
            }
          },
          "to": [
            {
              "key_code": "left_command"
            }
          ]
        },
        {
          "type": "basic",
          "conditions": [
            {
              "type": "frontmost_application_if",
              "bundle_identifiers": [
                "^tv\\.parsec\\.www$",
                "",
                "",
                "",
                "",
                ""
              ]
            }
          ],
          "from": {
            "key_code": "right_control",
            "modifiers": {
              "optional": [
                "any"
              ]
            }
          },
          "to": [
            {
              "key_code": "right_command"
            }
          ]
        }
      ]
    }
  ]
}
```
