### ISSUE TITLE
cmd+§ -> cmd+`

### ISSUE THREAD

**Issue by huehnerlady** [pqrs-org/KE-complex_modifications#951]
Hi,

I have a logitech keyboard and there I have the problem, that the ` and the § keys are swapped:
<details>
<summary> Image of keyboard</summary>

![image](https://user-images.githubusercontent.com/12533979/136379593-167d03f4-955a-4b8e-bf01-aee34466b059.png)
</details>

With mac change window is cmd+` but with this keyboard layout this is a bit of a twist for the fingers, cmd+§ is a lot more comfortable.

I tried to find a rule in the website, but couldn' find anything. so I thought I give writing it on my own a go:

<details>
<summary> Rule</summary>

```json
{
  "title": "change window on logitech",
  "rules": [
    {
      "description": "change cmd + § to cmd + `",
      "manipulators": [
        {
          "type": "basic",
          "from": {
            "key_code": "§",
            "modifiers": {
              "mandatory": [
                "command"
              ]
            }
          },
          "to": [
            {
              "key_code": "`",
              "modifiers": [
                "command"
              ]
            }
          ]
        }
      ]
    }
  ]
}
```
</details>
Unfortunately this does not work, in the logs I get the error

> [2021-10-07 13:48:56.739] [error] [grabber] karabiner.json error: `from` error: `key_code` error: unknown key_code: `"§"`

what am I doing wrong?

**Comment by paulchiu** [comment]
Can you please try loading Karabiner EventViewer, pressing the key, and seeing the name that shows up?

What you are looking for is the reported key code when you press that key.

![image](https://user-images.githubusercontent.com/3478672/136466850-a9c20f73-9b6b-49e4-b203-08fae510fda2.png)
