### ISSUE TITLE
Allow Non-Published Custom JSON to be Imported to KE Complex Modifications

### ISSUE THREAD

**Issue by mbwmbw1337** [pqrs-org/KE-complex_modifications#974]
I have some local JSON complex modifications that I'd like to be able to copy/paste into "Your Modification" window? This would just save one step.

<img width="1363" alt="Screen Shot 2021-11-09 at 20 29 03" src="https://user-images.githubusercontent.com/6092663/140898405-cc525e9b-6005-4227-bc3d-64a746fc8bf2.png">

**Comment by MuhammedZakir** [comment]
That is not created/maintained by the Karabiner-Elements author. For suggestions about that app, post in that apps' repo - https://github.com/genesy/karabiner-complex-rules-generator.

**Comment by mbwmbw1337** [comment]
Thank you! Will post over there.
