### ISSUE TITLE
Finder actions work improperly

### ISSUE THREAD

**Issue by ice-ivanov** [pqrs-org/KE-complex_modifications#976]
I've installed Karabiner to modify my Finder with key bindings so I have to use the touchpad less. I've imported shortcuts from this library and appears they don't work as intended:

- Use Return as Open - it opens folders but also calls Mission Control, so it breaks the flow and unfocuses from the window. I've checked mission control settings and there's no binding issue there (I've set it to right command and it still works).
- Use Return as Open and Use Fn+Return as Rename - Neither of these functions work. When combined with the option above, the above option works in the same weird way.
- Use Backspace to go to previous folder - doesn't do anything. Which is weird considering Return at least does something.
- Use Delete as Move to trash - doesn't work either. There's no dedicated Delete button but Fn+Backspace acts as Delete. Maybe the reason is my keyboard.

So the functionality that I was hoping to achieve didn't work out well. Does anyone have suggestions or maybe a working script that I can import?

MacBook Pro 2019 on Intel, Big Sur.

**Comment by honsa** [comment]
Have you tried the other definitions?

https://ke-complex-modifications.pqrs.org/?q=finder

Also had problem on rename open and still with touchbar function keys.

**Comment by Dorofei1543** [comment]
**I am sure that the problem will be solved if you continue to lie to people and do not comply with the conditions that you agreed on earlier, you are 34 years old, but you are like a child trying to deceive everyone, because you are the smartest**

**Comment by Dorofei1543** [comment]
**I am sure that the problem will be solved if you continue to lie to people and do not comply with the conditions that you agreed on earlier, you are 34 years old, but you are like a child trying to deceive everyone, because you are the smartest**

**Comment by Dorofei1543** [comment]
**I am sure that the problem will be solved if you continue to lie to people and do not comply with the conditions that you agreed on earlier, you are 34 years old, but you are like a child trying to deceive everyone, because you are the smartest**

**Comment by Dorofei1543** [comment]
**I am sure that the problem will be solved if you continue to lie to people and do not comply with the conditions that you agreed on earlier, you are 34 years old, but you are like a child trying to deceive everyone, because you are the smartest**

**Comment by Dorofei1543** [comment]
**I am sure that the problem will be solved if you continue to lie to people and do not comply with the conditions that you agreed on earlier, you are 34 years old, but you are like a child trying to deceive everyone, because you are the smartest**

**Comment by Dorofei1543** [comment]
**I am sure that the problem will be solved if you continue to lie to people and do not comply with the conditions that you agreed on earlier, you are 34 years old, but you are like a child trying to deceive everyone, because you are the smartest**

**Comment by Dorofei1543** [comment]
**I am sure that the problem will be solved if you continue to lie to people and do not comply with the conditions that you agreed on earlier, you are 34 years old, but you are like a child trying to deceive everyone, because you are the smartest**
