### ISSUE TITLE
Using a Bluetooth numeric keypad  but karabiner keeps activating Numeric keypad ON for some reason

### ISSUE THREAD

**Issue by arongkatz** [pqrs-org/KE-complex_modifications#979]
So basically i can start using the numeric keypad fine until i connect a second full keyboard, thats when for some reason karabiner activates these non existing key on the numeric keypad (it doesnt have a numeric keypad on) but it activates it and this makes my mac to keep making a sound like when you press a button that shouldnt be pressed (like trying to paste something out of an empty clipboard) 

Any way to fix this?

**Comment by MuhammedZakir** [comment]
Please move this issue to Karabiner-Elements repo.
