### ISSUE TITLE
Web interface uses 110% CPU and is sluggish on Safari 15.1

### ISSUE THREAD

**Issue by Patronics** [pqrs-org/KE-complex_modifications#980]
The [web interface](https://ke-complex-modifications.pqrs.org/) for viewing and downloading these modifications is very sluggish and unresponsive on MacOS Monterey, using up to 110% of my CPU time on an M1 Macbook Pro (It's just about the only thing that seems to make this computer sluggish!).

It seems more acceptably performant in Firefox on the same system.

**Comment by tekezo** [comment]
Thank you for feedback!

Recently, the frontend has been rewritten from Vue to React.
I think this issue has been solved in that case.
Please let me know if the issue still occurs in your environment.

**Comment by honsa** [comment]
Also using Monterey.

The new web interface works well on my machine.
