### ISSUE TITLE
[Feature request] Support for sidecar and apple pencil as input / device

### ISSUE THREAD

**Issue by not-that-nda** [pqrs-org/KE-complex_modifications#984]
In order to overcome the limitations of the current implementation of sidecar it would be great if both the ipad (as a secondary screen) and the apple pencil (as an input method) would be supported to:

1. Emulate RMB or MMB clicks with key combinations and apple pencil inputs (e.g. emulate RMB or MMB when tapping or dragging on the screen with the apple pencil, especially useful in design applications)
2. Capture touch inputs on the screen as mappeable events (e.g. combine using a single finger on the screen plus the pen input as RMB, or two finger tap as a mappeable event such as "undo - ctrl+Z"

This remapping would make the ipad a much more suitable standalone sidecar input method than the current implementation by apple where it is hard to use unless the app has specific support for it, and is not the case in most apps.

**Comment by MuhammedZakir** [comment]
You should move this to `Karabiner-Elements` repo. This repo is for complex modifications only.

**Comment by not-that-nda** [comment]
Thanks for the suggestion. Moved to: https://github.com/pqrs-org/Karabiner-Elements/issues/2914
